#!/usr/bin/env python3
"""Driver for the assembled temp_por_top supply-ramp campaign (issue #98).

The rate x process x temperature x supply grid is expressed as ``klt sim``
requests (one request per ramp rate: process x supply x temperature are klt's
own corner axes) and goes to the Spot batch fleet; this script never launches
ngspice over the grid itself.  The ramp-rate axis stays local to this
experiment: it is a ``.param rate`` written into one generated netlist per
request, not an extension of sim/bin/corner-run.py.

Stages (each is a subcommand):

  run        build netlists + requests, submit them to the fleet (explicit
             ``--backend batch``), keep the raw outputs under sim/build/.
  crosscheck one single-corner LOCAL probe (``--backend local``) compared with
             the fleet's result for the same point.
  record     grade every retrieved waveform with ramp_checker.py and write the
             append-only evidence: netlist snapshots, per-point logs, event-
             preserving traces, markdown + JSON record twins.
  selftest   run the transition checker on controlled waveforms (including a
             deliberate double release) and write a self-test record.

A batch submit failure is reported in the record; there is no local fallback.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import gzip
import json
import os
import re
import shutil
import subprocess
import sys
import threading
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR / "bin"))
sys.path.insert(0, str(HERE))

import ramp_checker as rc  # noqa: E402
import sim_common  # noqa: E402

cr = sim_common.load_corner_run()

SLUG = "supply-ramp-top"
MANIFEST = HERE / "experiment.json"
TB_SCH = HERE / "testbench" / "tb_temp_por_ramp.sch"
DUT_NETLIST = REPO_ROOT / "design" / "netlist" / "temp_por_top.spice"
BUILD = REPO_ROOT / "sim" / "build" / SLUG
HOLD_S = 15e-3
RATE_CEIL_SUPPLY = 3.63
TMAX_S = 5e-6
MODEL_LIB = "libs.tech/combined/sky130.lib.spice"

_print_lock = threading.Lock()


def say(msg: str) -> None:
    with _print_lock:
        print(msg, flush=True)


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def rate_tag(rate: float) -> str:
    return "r" + f"{rate:g}".replace("+", "")


def corner_id(proc: str, temp: float, vf: float) -> str:
    return f"{proc}_{cr.fmt_temp(temp)}c_{vf:.2f}v"


def tstop_for(rate: float) -> float:
    return RATE_CEIL_SUPPLY / rate + HOLD_S


def all_rates(man: dict) -> list[tuple[float, float | None]]:
    """[(rate, primary_rate_or_None)] -- primaries first, each followed by its half-rate guard."""
    out = []
    factor = man["rates"]["half_rate_guard_factor"]
    for r in man["rates"]["primary_v_per_s"]:
        out.append((r, None))
        out.append((r * factor, r))
    return out


# --------------------------------------------------------------------------
# netlists and requests
# --------------------------------------------------------------------------


def tb_netlist_head(run_dir: Path, pdk) -> str:
    """Netlist the testbench schematic with xschem; keep only the testbench part.

    The DUT subcircuits come from the committed design/netlist/temp_por_top.spice
    export (xschem 3.4.4 on this host leaves ``expr()`` device-parameter forms
    that ngspice cannot evaluate; the committed export was produced by 3.4.7).
    """
    out_dir = run_dir / "tb"
    produced = cr.netlist_with_xschem(TB_SCH, out_dir, pdk)
    text = produced.read_text().replace(str(REPO_ROOT) + os.sep, "")
    head = text.split("\n* expanding")[0]
    return "\n".join(ln for ln in head.splitlines() if ln.strip().lower() != ".end") + "\n"


def build_netlist(head: str, variant: dict, rate: float) -> str:
    dut = DUT_NETLIST.read_text()
    dut = "\n".join(ln for ln in dut.splitlines() if ln.strip().lower() != ".end") + "\n"
    edit = variant.get("netlist_edit")
    if edit:
        if dut.count(edit["find"]) != 1:
            raise SystemExit(f"variant edit target not found exactly once: {edit['find']!r}")
        dut = dut.replace(edit["find"], edit["replace"])
    banner = (
        f"* {SLUG}: generated by sim/supply-ramp-top/run_ramp_campaign.py -- do not edit\n"
        f"* ramp rate (V/s): {rate:g}   variant edit: {'none' if not edit else edit['find'] + ' -> ' + edit['replace']}\n"
        f".param rate={rate:g}\n"
        "* ng_nomodcheck: same setting as sim/spiceinit; carried in the netlist because the\n"
        "* fleet runner ignores options.ngspice_init (see experiment.json ngspice_note)\n"
        ".control\nset ng_nomodcheck\n.endc\n"
    )
    return banner + head + "\n" + dut


def build_request(netlist_name: str, rate: float, man: dict, backend: str, capacity_wait_s: float = 0) -> dict:
    tstop = tstop_for(rate)
    t_at = f"{(tstop - 0.1e-3):.9g}"
    c = man["corners"]
    req = {
        "netlist": netlist_name,
        "backend": backend,
        "models": {"pdk": "sky130A", "lib": MODEL_LIB},
        "corners": {
            "process": c["process"],
            "supply_v": {"vset": c["supply_v"]},
            "temperature_c": c["temperature_c"],
        },
        "analysis": {"kind": "tran", "args": f"1u {tstop:.9g} 0 {TMAX_S:.3g}"},
        "measurements": [
            {"name": "vdd_end", "spice": f".meas tran vdd_end FIND v(vdd) AT={t_at}", "unit": "V"},
            {"name": "resetn_end", "spice": f".meas tran resetn_end FIND v(resetn) AT={t_at}", "unit": "V"},
            {"name": "resetn_max", "spice": ".meas tran resetn_max MAX v(resetn)", "unit": "V"},
            {"name": "por_raw_max", "spice": ".meas tran por_raw_max MAX v(xdut.por_raw)", "unit": "V"},
            {"name": "ibias_end", "spice": f".meas tran ibias_end FIND v(xdut.ibias) AT={t_at}", "unit": "V"},
        ],
        "options": {"timeout_s": 1500, "keep_artifacts": True, "waveforms": True},
    }
    if backend == "batch":
        req["batch"] = {"runner_version_check": "warn"}
        if capacity_wait_s:
            req["batch"]["capacity_wait_s"] = capacity_wait_s
    return req


def klt_version() -> str:
    p = subprocess.run(["klt", "--version"], capture_output=True, text=True)
    return p.stdout.strip() or p.stderr.strip()


def submit(variant_name: str, rate: float, head: str, man: dict, run_dir: Path, capacity_wait_s: float = 0) -> dict:
    tag = rate_tag(rate)
    d = run_dir / variant_name / tag
    d.mkdir(parents=True, exist_ok=True)
    # a previous attempt that never produced a usable report is archived, not overwritten
    prev = d / "report.json"
    if prev.is_file():
        n = 1
        while (d / f"attempt{n}").exists():
            n += 1
        arch = d / f"attempt{n}"
        arch.mkdir()
        for name in ("report.json", "klt.stderr"):
            if (d / name).is_file():
                shutil.move(str(d / name), str(arch / name))
    netlist = d / "netlist.spice"
    netlist.write_text(build_netlist(head, man["variants"][variant_name], rate))
    req = build_request("netlist.spice", rate, man, "batch", capacity_wait_s)
    (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
    cmd = ["klt", "sim", str(d / "request.json"), "--backend", "batch", "-o", str(d / "out"), "--format", "json"]
    say(f"[submit] {variant_name} {tag}: {len(man['corners']['process']) * 9} points -> batch fleet")
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=4 * 3600)
    (d / "report.json").write_text(p.stdout)
    (d / "klt.stderr").write_text(p.stderr)
    status = "?"
    try:
        status = json.loads(p.stdout).get("status", "?")
    except json.JSONDecodeError:
        status = "NO-JSON"
    say(f"[done]   {variant_name} {tag}: exit {p.returncode}, report status {status}")
    return {"variant": variant_name, "rate": rate, "tag": tag, "exit": p.returncode, "status": status}


def cmd_run(args) -> int:
    man = load_manifest()
    pdk = cr.resolve_pdk(cr.load_pin())
    git_info = cr.git_state()
    now = datetime.now(timezone.utc)
    run_id = args.run_id or f"{now:%Y%m%d-%H%M%S}-{git_info['sha']}"
    run_dir = BUILD / run_id
    if args.retry_failed:
        if not run_dir.exists():
            raise SystemExit(f"{run_dir} does not exist")
    else:
        if run_dir.exists():
            raise SystemExit(f"{run_dir} exists; refusing to reuse a run id")
        run_dir.mkdir(parents=True)
    head = tb_netlist_head(run_dir, pdk) if not args.retry_failed else tb_netlist_head(run_dir / "retry", pdk)
    variants = args.variant or list(man["variants"])
    work = [(v, r) for v in variants for r, _ in all_rates(man)]
    if args.retry_failed:
        def usable(v, r):
            rp = run_dir / v / rate_tag(r) / "report.json"
            if not rp.is_file():
                return False
            try:
                return "corners" in json.loads(rp.read_text())
            except json.JSONDecodeError:
                return False
        work = [(v, r) for v, r in work if not usable(v, r)]
        say(f"retrying {len(work)} request(s) without a usable report, capacity_wait_s={args.capacity_wait}")
    meta = {
        "run_id": run_id,
        "started_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "variants": variants,
        "klt_client": klt_version(),
        "klt_sim_backend_env": os.environ.get("KLT_SIM_BACKEND"),
        "work": [[v, r] for v, r in work],
    }
    if not args.retry_failed:
        (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")
    say(f"run id {run_id}: {len(work)} requests ({len(variants)} variant(s) x {len(work) // len(variants)} rates)")
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, args.jobs)) as ex:
        futs = [ex.submit(submit, v, r, head, man, run_dir, args.capacity_wait) for v, r in work]
        for f in futs:
            try:
                results.append(f.result())
            except Exception as err:  # noqa: BLE001 -- recorded, never swallowed
                results.append({"error": repr(err)})
                say(f"[error] submit raised: {err!r}")
    meta["submit_results" if not args.retry_failed else "retry_results"] = results
    if args.retry_failed:
        old = json.loads((run_dir / "run.json").read_text())
        old.setdefault("retries", []).append({"at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "capacity_wait_s": args.capacity_wait, "results": results})
        meta = old
    (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")
    print(f"raw outputs: {run_dir}")
    return 0


# --------------------------------------------------------------------------
# local cross-check (one corner, --backend local)
# --------------------------------------------------------------------------


def cmd_crosscheck(args) -> int:
    man = load_manifest()
    pdk = cr.resolve_pdk(cr.load_pin())
    run_dir = BUILD / args.run_id
    if not run_dir.exists():
        raise SystemExit(f"no such run: {run_dir}")
    variant = "diag-mn1-l20"
    rate = 1e4
    head = tb_netlist_head(run_dir / "xc", pdk)
    d = run_dir / "crosscheck"
    d.mkdir(exist_ok=True)
    (d / "netlist.spice").write_text(build_netlist(head, man["variants"][variant], rate))
    req = build_request("netlist.spice", rate, man, "local")
    req["corners"] = {"process": ["tt"], "supply_v": {"vset": [3.3]}, "temperature_c": [27]}
    req["options"]["ngspice_init"] = [
        ln.strip() for ln in (SIM_DIR / "spiceinit").read_text().splitlines() if ln.strip() and not ln.startswith("*")
    ]
    (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
    say("[crosscheck] one local corner (tt/27C/3.30V, 10 kV/s, diag-mn1-l20) on local ngspice")
    p = subprocess.run(
        ["klt", "sim", str(d / "request.json"), "--backend", "local", "-o", str(d / "out"), "--format", "json"],
        capture_output=True,
        text=True,
        timeout=3600,
    )
    (d / "report.json").write_text(p.stdout)
    print(f"exit {p.returncode}")
    return 0


# --------------------------------------------------------------------------
# record
# --------------------------------------------------------------------------


def scrub(text: str, run_dir: Path) -> str:
    text = text.replace(str(run_dir), "<build>")
    text = text.replace(str(REPO_ROOT) + os.sep, "")
    return re.sub(r"/home/[^/\s]+", "<home>", text)


def point_log(corner: dict, d_out: Path, header: list[str], run_dir: Path) -> str:
    art = corner.get("artifacts") or {}
    deck = Path(art["deck"]).read_text() if art.get("deck") and Path(art["deck"]).is_file() else "(no deck retrieved)"
    log = Path(art["log"]).read_text() if art.get("log") and Path(art["log"]).is_file() else "(no ngspice log retrieved)"
    lines = list(header) + [""]
    lines += ["# ==== klt sim deck (exact input given to ngspice on the runner) ====", *[f"| {ln}" for ln in deck.splitlines()], ""]
    lines += ["# ==== klt diagnostics ====", *[f"| {dg.get('severity')}/{dg.get('code')}: {dg.get('message')}" for dg in corner.get("diagnostics", [])], ""]
    lines += ["# ==== ngspice stdout+stderr ====", log.rstrip(), ""]
    return scrub("\n".join(lines), run_dir)


def classify_error(corner: dict, log_text: str) -> str:
    if "could not find a valid modelname" in log_text:
        return "model_not_found (no valid model bin for a drawn device geometry)"
    codes = [d.get("code") for d in corner.get("diagnostics", [])]
    if any(c and "timeout" in c for c in codes):
        return "timeout"
    return "error:" + ",".join(sorted({c for c in codes if c})) if codes else "error"


def analyze_variant(variant: str, run_dir: Path, man: dict, corners_dir: Path, write: bool) -> dict:
    points, requests = [], []
    pdk_info = {}
    for rate, primary in all_rates(man):
        tag = rate_tag(rate)
        d = run_dir / variant / tag
        rep_path = d / "report.json"
        req_rec = {"rate_v_per_s": rate, "tag": tag, "primary_rate": primary, "tstop_s": tstop_for(rate)}
        attempts = []
        for ad in sorted(d.glob("attempt*")):
            try:
                body = json.loads((ad / "report.json").read_text()) if (ad / "report.json").is_file() else {}
                msg = (body.get("error") or {}).get("message") or ("report status " + str(body.get("status")))
            except json.JSONDecodeError:
                msg = "unparseable report"
            attempts.append(scrub(msg, run_dir)[:400])
        if attempts:
            req_rec["failed_earlier_attempts"] = attempts
        if not rep_path.is_file():
            req_rec["outcome"] = "NOT SUBMITTED / no report"
            requests.append(req_rec)
            continue
        try:
            rep = json.loads(rep_path.read_text())
        except json.JSONDecodeError:
            req_rec["outcome"] = "NO JSON (klt failed before a report existed): " + scrub((d / "klt.stderr").read_text()[-600:], run_dir)
            requests.append(req_rec)
            continue
        if "corners" not in rep:
            req_rec["outcome"] = "klt error (no corners reported): " + scrub(str((rep.get("error") or {}).get("message", rep))[:500], run_dir)
            requests.append(req_rec)
            continue
        remote = (rep.get("environment") or {}).get("remote") or {}
        req_rec.update(
            {
                "outcome": rep.get("status"),
                "job_id": remote.get("job_id"),
                "instance_type": remote.get("instance_type"),
                "lifecycle": remote.get("lifecycle"),
                "runner_klt_version": remote.get("runner_klt_version"),
                "client_klt_version": remote.get("client_klt_version"),
                "elapsed_seconds": remote.get("elapsed_seconds"),
                "state": remote.get("state"),
                "corner_count": rep.get("corner_count"),
            }
        )
        pdk_info = (rep.get("provenance") or {}).get("pdk", pdk_info)
        requests.append(req_rec)
        for c in rep.get("corners", []):
            proc = c["process"]
            vf = c["supply_v"]["vset"]
            temp = c["temperature_c"]
            cid = corner_id(proc, temp, vf)
            art = c.get("artifacts") or {}
            wave_path = Path(art["waveform"]) if art.get("waveform") else None
            log_text = Path(art["log"]).read_text() if art.get("log") and Path(art["log"]).is_file() else ""
            ngv = re.findall(r"(ngspice-\d+) done", log_text)
            pt = {
                "id": cid,
                "variant": variant,
                "rate_v_per_s": rate,
                "rate_tag": tag,
                "primary_rate": primary,
                "process": proc,
                "temperature_c": temp,
                "supply_v": vf,
                "klt_status": c.get("status"),
                "runtime_s": c.get("runtime_s"),
                "ngspice": ngv[0] if ngv else None,
                "measurements": {m["name"]: m.get("value") for m in c.get("measurements", [])},
                "diagnostics": [{"severity": dg.get("severity"), "code": dg.get("code"), "message": scrub(dg.get("message", ""), run_dir)[:400]} for dg in c.get("diagnostics", [])],
            }
            res = None
            if wave_path is not None and wave_path.is_file():
                wave = rc.load_wave(wave_path)
                res = rc.analyze(wave, vf, rate)
                if "resetn" in res:
                    rows = rc.compress(wave)
                    st = rc.transitions_from_stored(rows, vf)
                    res["stored_trace"] = {
                        "rows": len(rows),
                        "full_samples": len(wave["time"]),
                        "n_release": st["n_release"],
                        "n_reassert": st["n_reassert"],
                        "n_runt": st["n_runt"],
                        "premature": st["premature"],
                        "agrees_with_full_resolution": (
                            st["n_release"] == res["resetn"]["n_release"]
                            and st["n_reassert"] == res["resetn"]["n_reassert"]
                            and st["n_runt"] == res["resetn"]["n_runt"]
                            and st["premature"] == res["resetn"]["premature"]
                        ),
                    }
                    if write:
                        rc.write_trace(corners_dir / tag / f"{cid}.trace.csv.gz", rows)
            if res is None:
                pt["outcome"] = "ERROR"
                pt["error_class"] = classify_error(c, log_text)
                pt["check"] = None
            else:
                pt["outcome"] = res["verdict"]
                pt["check"] = res
            if write:
                header = [
                    f"# point: {SLUG} {variant} {tag} {cid}",
                    f"# process={proc} temp={cr.fmt_temp(temp)}C final_supply={vf:.2f}V rate={rate:g} V/s tstop={tstop_for(rate):.6g}s",
                    f"# klt status: {c.get('status')}   runtime on runner: {c.get('runtime_s')} s   outcome: {pt['outcome']}",
                ]
                (corners_dir / tag).mkdir(parents=True, exist_ok=True)
                (corners_dir / tag / f"{cid}.log").write_text(point_log(c, run_dir, header, run_dir))
            points.append(pt)
    return {"points": points, "requests": requests, "fleet_pdk_report": pdk_info}


def grade_pairs(points: list[dict], man: dict) -> list[dict]:
    q = man["grading"]["quasi_static"]
    lo, hi = q["release_delay_ratio_band"]
    tol = q["vdd_at_por_raw_rise_tolerance_v"]
    by = {(p["rate_v_per_s"], p["id"]): p for p in points}
    pairs = []
    for p in points:
        if p["primary_rate"] is not None:
            continue
        half = by.get((p["rate_v_per_s"] * man["rates"]["half_rate_guard_factor"], p["id"]))
        rec = {"id": p["id"], "rate_v_per_s": p["rate_v_per_s"], "half_rate_v_per_s": p["rate_v_per_s"] * man["rates"]["half_rate_guard_factor"]}
        a, b = p.get("check"), (half or {}).get("check")
        if not a or not b or "resetn" not in a or "resetn" not in b:
            rec.update(grade="n/a (a segment has no waveform)", por_raw_vdd_grade="n/a", delay_grade="n/a")
            pairs.append(rec)
            continue
        ra, rb = a["por_raw"], b["por_raw"]
        if ra["t_rise_mid_s"] is None or rb["t_rise_mid_s"] is None:
            rec["por_raw_vdd_grade"] = "n/a (POR_RAW never rose in a segment)"
        elif ra["rise_after_ramp_end_censored"] or rb["rise_after_ramp_end_censored"]:
            rec["por_raw_vdd_grade"] = "censored (POR_RAW rose after the ramp ended in a segment: no VDD threshold measured)"
            rec["vdd_at_rise_full_v"], rec["vdd_at_rise_half_v"] = ra["vdd_at_rise_v"], rb["vdd_at_rise_v"]
        elif not (ra["vdd_at_rise_resolved"] and rb["vdd_at_rise_resolved"]):
            rec["por_raw_vdd_grade"] = "unresolved (too few ramp samples to interpolate the crossing)"
            rec["vdd_at_rise_full_v"], rec["vdd_at_rise_half_v"] = ra["vdd_at_rise_v"], rb["vdd_at_rise_v"]
        else:
            dv = ra["vdd_at_rise_v"] - rb["vdd_at_rise_v"]
            rec["vdd_at_rise_full_v"], rec["vdd_at_rise_half_v"], rec["vdd_at_rise_delta_v"] = ra["vdd_at_rise_v"], rb["vdd_at_rise_v"], dv
            rec["por_raw_vdd_grade"] = "consistent" if abs(dv) <= tol else "rate-dependent"
        da, db = a["release_delay_s"], b["release_delay_s"]
        if da is None or db is None or db == 0:
            rec["delay_grade"] = "n/a (a segment has no release)"
        else:
            ratio = da / db
            rec["release_delay_full_s"], rec["release_delay_half_s"], rec["release_delay_ratio"] = da, db, ratio
            rec["delay_grade"] = "consistent" if lo <= ratio <= hi else "rate-dependent"
        rec["grade"] = rec["por_raw_vdd_grade"] if not rec["por_raw_vdd_grade"].startswith("consistent") else rec["delay_grade"]
        pairs.append(rec)
    return pairs


def summarize(points: list[dict]) -> dict:
    out: dict = {}
    for p in points:
        s = out.setdefault(p["rate_tag"], {"rate_v_per_s": p["rate_v_per_s"], "n": 0, "outcome": {}, "transition_verdict": {}, "fail_codes": {}, "nonphysical": 0})
        s["n"] += 1
        s["outcome"][p["outcome"]] = s["outcome"].get(p["outcome"], 0) + 1
        if p["outcome"] == "ERROR":
            k = p.get("error_class", "error")
            s["fail_codes"][k] = s["fail_codes"].get(k, 0) + 1
            continue
        chk = p["check"]
        if "transition_verdict" not in chk:
            continue
        s["transition_verdict"][chk["transition_verdict"]] = s["transition_verdict"].get(chk["transition_verdict"], 0) + 1
        for code in chk["fail_codes"]:
            s["fail_codes"][code] = s["fail_codes"].get(code, 0) + 1
        if not chk["physical"]["ok"]:
            s["nonphysical"] += 1
    return out


def fmt(x, spec=".4g", unit=""):
    return "n/a" if x is None else f"{x:{spec}}{unit}"


def render_md(rec: dict) -> str:
    L = [f"# Record {rec['record_id']}", ""]
    L += sim_common.render_record_id_experiment(rec["record_id"], rec["experiment"]["slug"], rec["experiment"]["title"])
    L.append(f"- **Claim**: {rec['experiment']['claim']}")
    L.append(f"- **Variant**: `{rec['variant']['name']}` -- {rec['variant']['description']}")
    L.append(f"- **Netlist provenance**: {rec['experiment']['provenance']} (`{rec['experiment']['provenance_source']}`)")
    L += sim_common.render_pdk_tools_repo_state(rec)
    t = rec["tools"]
    L.append(f"- **Fleet runner**: klt `{t['fleet_runner_klt']}` / `{t['fleet_ngspice']}` (client klt `{t['klt_client']}`); {t['fleet_note']}")
    L.append(f"- **Host tool caveat**: {t['xschem_note']}")
    m = rec["matrix"]
    L.append("- **Corner matrix run**:")
    L.append(f"  - Process: {', '.join(m['process'])}  (PNP rides the same sections; no `ll`/`hh` resistor-skew cross product -- see Absent coverage)")
    L.append("  - Temperature: " + ", ".join(f"{cr.fmt_temp(x)} C" for x in m["temperature_c"]))
    L.append("  - Supply (final): " + ", ".join(f"{v:.2f} V" for v in m["supply_v"]))
    L.append("  - Ramp rates (V/s, EXPLORATORY): " + ", ".join(f"{r:g}" for r in m["rates_v_per_s"]) + "  (each primary paired with its half-rate guard)")
    L.append(f"  - {m['n_points']} point(s) declared, {m['n_points_with_waveform']} with a retrieved waveform, {m['n_points_error']} without (reported as ERROR below)")
    L.append("  - Full declared rate x PVT matrix; no subset.")
    L.append("- **Statistical convention**: N/A (corner-matrix check)")
    L.append("")
    L.append("## Measurement definitions (exploratory; none is a ratified bound)")
    for k, v in rec["definitions"].items():
        L.append(f"- **{k}**: {v}")
    L.append("")
    L.append("## Per-request fleet submissions")
    L.append("| rate (V/s) | tstop (ms) | outcome | job id | runner klt | state |")
    L.append("|---|---|---|---|---|---|")
    for r in rec["requests"]:
        L.append(f"| {r['rate_v_per_s']:g} | {r['tstop_s'] * 1e3:.4g} | {r.get('outcome')} | {r.get('job_id')} | {r.get('runner_klt_version')} | {r.get('state')} |")
    L.append("")
    L.append("## Result summary by rate")
    L.append("| rate (V/s) | points | outcomes | transition verdicts | failure codes / error classes | nonphysical-node points |")
    L.append("|---|---|---|---|---|---|")
    for tag, s in rec["summary"].items():
        L.append(f"| {s['rate_v_per_s']:g} | {s['n']} | {s['outcome']} | {s['transition_verdict']} | {s['fail_codes']} | {s['nonphysical']} |")
    L.append("")
    L.append("## Per-point results")
    L.append("Columns: transition verdict / overall; n_rel = RESETn releases (V_IH), n_re = re-asserts, t_rel = release time (V_IH crossing), VDD@raw = supply when POR_RAW crossed V_MID, delay = POR_RAW->RESETn (V_MID) delay, IBIAS step = IBIAS change across the release, swings = IBIAS reversals > 5 mV after POR_RAW rises.")
    for tag in rec["summary"]:
        pts = [p for p in rec["points"] if p["rate_tag"] == tag]
        L.append("")
        L.append(f"### rate {pts[0]['rate_v_per_s']:g} V/s" + (f" (half-rate guard of {pts[0]['primary_rate']:g})" if pts[0]["primary_rate"] else ""))
        L.append("| point | outcome | transition | n_rel | n_re | t_rel (ms) | VDD@raw (V) | delay (ms) | IBIAS step (mV) | swings | physical | note |")
        L.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
        for p in pts:
            c = p["check"]
            if not c or "resetn" not in c:
                L.append(f"| {p['id']} | {p['outcome']} | - | - | - | - | - | - | - | - | - | {p.get('error_class', '')} |")
                continue
            r, rw = c["resetn"], c["por_raw"]
            note = ",".join(c["fail_codes"]) or ",".join(c["unresolved_reasons"])
            vraw = fmt(rw["vdd_at_rise_v"], ".3f") + ("*" if rw["rise_after_ramp_end_censored"] else "")
            L.append(
                f"| {p['id']} | {p['outcome']} | {c['transition_verdict']} | {r['n_release']} | {r['n_reassert']} | {fmt(r['t_release_s'] and r['t_release_s'] * 1e3, '.4g')} | {vraw} | "
                f"{fmt(c['release_delay_s'] and c['release_delay_s'] * 1e3, '.4g')} | {fmt(c['ibias']['release_step_v'] and c['ibias']['release_step_v'] * 1e3, '.3g')} | {c['ibias']['swings_gt_5mV']} | {'ok' if c['physical']['ok'] else 'NONPHYSICAL'} | {note} |"
            )
    L.append("")
    L.append("`*` = POR_RAW rose after the ramp had ended (VDD at its final value): censored, not a VDD threshold.")
    L.append("")
    L.append("## Quasi-static (half-rate guard) grading")
    cnt = {}
    for pr in rec["pairs"]:
        k = (pr["rate_v_per_s"], pr["por_raw_vdd_grade"].split(" ")[0], pr["delay_grade"].split(" ")[0])
        cnt[k] = cnt.get(k, 0) + 1
    L.append("| primary rate (V/s) | VDD@POR_RAW grade | release-delay grade | points |")
    L.append("|---|---|---|---|")
    for (rate, g1, g2), n in sorted(cnt.items(), key=lambda kv: (-kv[0][0], kv[0][1], kv[0][2])):
        L.append(f"| {rate:g} | {g1} | {g2} | {n} |")
    L.append("")
    if rec.get("crosscheck"):
        x = rec["crosscheck"]
        L.append("## Local cross-check (single corner, `--backend local`)")
        L.append(x["text"])
        L.append("")
    L.append("## Absent coverage (stated, not hidden)")
    for a in rec["absent_coverage"]:
        L.append(f"- {a}")
    L.append("")
    if rec.get("follow_on"):
        L.append("## Measured follow-on recommendation")
        L.append(rec["follow_on"])
        L.append("")
    L.append("## Links")
    for k, v in rec["links"].items():
        L.append(f"- {k}: `{v}`")
    L.append(f"- **Timestamp / author**: {rec['timestamp']}, {rec['author']}")
    L.append(f"- **Supersedes**: {rec['supersedes'] or '(none)'}")
    L.append("")
    L.append("Written by `sim/supply-ramp-top/run_ramp_campaign.py`. Append-only: never edit this file -- a correction is a new record with a `Supersedes` field (see `sim/README.md`).")
    L.append("")
    return "\n".join(L)


ABSENT = [
    "The orthogonal passive-skew (`ll`/`hh`) resistor/capacitor axis is NOT crossed with the ramp-rate axis: this first increment is not the complete spec/porting-plan.md Sec3.1 x Sec3.3 grid.",
    "Rates below 500 V/s and above 1 MV/s are not simulated; the primary rate set is exploratory and no numeric ramp envelope is claimed or ratified (DR-003 Sec8).",
    "Brownout / dip behavior (Sec3.4) and mismatch Monte Carlo statistics are separate follow-on scopes and are not exercised here.",
    "PTAT/CTAT are left open-circuit; the temp_core startup artifacts of issue #86 are not solved here -- any affected point shows up as a 'nonphysical' node, a klt diagnostic, or a missing result in the per-point tables.",
]


def cmd_record(args) -> int:
    man = load_manifest()
    run_dir = BUILD / args.run_id
    meta = json.loads((run_dir / "run.json").read_text())
    pin = cr.load_pin()
    pdk = cr.resolve_pdk(pin)
    git_info = cr.git_state()
    now = datetime.now(timezone.utc)
    variants = args.variant or meta["variants"]
    follow = Path(args.follow_on_file).read_text().strip() if args.follow_on_file else ""
    xc = None
    xcp = run_dir / "crosscheck" / "report.json"
    out_ids = []
    for idx, variant in enumerate(variants):
        stamp = now if idx == 0 else datetime.now(timezone.utc)
        record_id = f"{stamp:%Y%m%d}-{stamp:%H%M%S}-{git_info['sha']}"
        if idx and record_id in out_ids:
            raise SystemExit("record id collision")
        rec_dir = HERE / "records"
        corners_dir = HERE / "corners" / record_id
        snap_dir = HERE / "netlist-snapshots" / record_id
        for pth in (rec_dir / f"{record_id}.md", rec_dir / f"{record_id}.json", corners_dir, snap_dir):
            if pth.exists():
                raise SystemExit(f"{pth} exists -- sim/ is append-only")
        res = analyze_variant(variant, run_dir, man, corners_dir, write=True)
        pts = res["points"]
        pairs = grade_pairs(pts, man)
        snap_dir.mkdir(parents=True, exist_ok=True)
        for rate, _ in all_rates(man):
            src = run_dir / variant / rate_tag(rate) / "netlist.spice"
            if src.is_file():
                shutil.copyfile(src, snap_dir / f"{variant}_{rate_tag(rate)}.spice")
                shutil.copyfile(run_dir / variant / rate_tag(rate) / "request.json", snap_dir / f"{variant}_{rate_tag(rate)}.request.json")
            rp = run_dir / variant / rate_tag(rate) / "report.json"
            if rp.is_file():
                (corners_dir / rate_tag(rate)).mkdir(parents=True, exist_ok=True)
                (corners_dir / rate_tag(rate) / "klt-report.json").write_text(scrub(rp.read_text(), run_dir))
        if xcp.is_file() and variant == "diag-mn1-l20":
            xrep = json.loads(xcp.read_text())
            xcor = (xrep.get("corners") or [None])[0]
            if xcor and xcor.get("artifacts", {}).get("waveform"):
                lw = rc.load_wave(Path(xcor["artifacts"]["waveform"]))
                la = rc.analyze(lw, 3.3, 1e4)
                fl = next((p for p in pts if p["id"] == "tt_27c_3.30v" and p["rate_v_per_s"] == 1e4), None)
                if fl and fl["check"]:
                    fc = fl["check"]
                    xc = {
                        "local": {"ngspice": "ngspice-42 (host)", "t_release_s": la["resetn"]["t_release_s"], "end_v": la["resetn"]["end_v"], "por_raw_vdd_v": la["por_raw"]["vdd_at_rise_v"], "verdict": la["transition_verdict"]},
                        "fleet": {"ngspice": fl["ngspice"], "t_release_s": fc["resetn"]["t_release_s"], "end_v": fc["resetn"]["end_v"], "por_raw_vdd_v": fc["por_raw"]["vdd_at_rise_v"], "verdict": fc["transition_verdict"]},
                    }
                    xc["text"] = (
                        f"tt / 27 C / 3.30 V / 10 kV/s, variant diag-mn1-l20: local {xc['local']['ngspice']} released at {xc['local']['t_release_s'] * 1e3:.5g} ms "
                        f"(RESETn end {xc['local']['end_v']:.5g} V, POR_RAW rose at VDD={xc['local']['por_raw_vdd_v']:.4g} V); fleet {xc['fleet']['ngspice']} released at "
                        f"{xc['fleet']['t_release_s'] * 1e3:.5g} ms (end {xc['fleet']['end_v']:.5g} V, VDD={xc['fleet']['por_raw_vdd_v']:.4g} V). "
                        "The fleet PDK commit is not reported by runner klt 0.5.0; agreement of the two engines here is the only evidence that the fleet model library matches the pin."
                    )
        n_wave = sum(1 for p in pts if p["check"] and "resetn" in p["check"])
        v = man["variants"][variant]
        ngs = sorted({p["ngspice"] for p in pts if p["ngspice"]})
        runners = sorted({r.get("runner_klt_version") for r in res["requests"] if r.get("runner_klt_version")})
        record = {
            "record_id": record_id,
            "timestamp": stamp.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "author": args.author or cr.default_author(),
            "supersedes": args.supersedes,
            "experiment": {k: man[k] for k in ("slug", "title", "claim", "provenance", "provenance_source", "statistical_convention")},
            "variant": {"name": variant, "description": v["description"], "netlist_edit": v["netlist_edit"]},
            "pdk": {"root": "<host $PDK_ROOT>", "variant": pdk.variant, "installed_commit": pdk.installed_commit, "pinned_commit": pin["open_pdks_commit"], "matches_pin": pdk.matches_pin, "lib_file": MODEL_LIB + " (resolved on the runner as /opt/pdk/sky130A/...)"},
            "tools": {
                "ngspice": f"{cr.first_line(['ngspice', '-v'])} (host; the grid ran on the fleet)",
                "xschem": cr.first_line(["xschem", "--version"]),
                "platform": cr.tool_versions()["platform"],
                "python": cr.tool_versions()["python"],
                "klt_client": meta["klt_client"],
                "fleet_runner_klt": ", ".join(runners) or "unknown",
                "fleet_ngspice": ", ".join(ngs) or "unknown",
                "fleet_note": "client/runner klt version skew accepted with batch.runner_version_check=warn; the 0.5.0 runner ignores options.ngspice_init and expr measurements, so only .meas cards and a netlist-carried `set ng_nomodcheck` are used",
                "xschem_note": "host xschem is 3.4.4 and leaves expr() device parameters unevaluated (the committed design/netlist export was made with 3.4.7), so only the testbench is netlisted by xschem here and the DUT is spliced from the committed design/netlist/temp_por_top.spice",
            },
            "git": git_info,
            "matrix": {
                "process": man["corners"]["process"],
                "temperature_c": man["corners"]["temperature_c"],
                "supply_v": man["corners"]["supply_v"],
                "rates_v_per_s": [r for r, _ in all_rates(man)],
                "n_points": len(all_rates(man)) * 45,
                "n_points_with_waveform": n_wave,
                "n_points_error": len(pts) - n_wave + (len(all_rates(man)) * 45 - len(pts)),
                "is_subset": False,
                "subset_reason": None,
            },
            "definitions": {
                "levels": man["grading"]["levels"],
                "release/re-assert/runt": man["grading"]["release"],
                "premature": man["grading"]["premature"],
                "resolution": man["grading"]["resolution"],
                "physicality": man["grading"]["physicality"],
                "quasi-static": man["grading"]["quasi_static"]["note"] + f" Tolerances: VDD@POR_RAW within {man['grading']['quasi_static']['vdd_at_por_raw_rise_tolerance_v']} V; delay ratio in {man['grading']['quasi_static']['release_delay_ratio_band']}.",
                "rate/window": man["rates"]["construction"] + " " + man["rates"]["observation_window"],
                "trace storage": "committed traces are change-triggered (dV>=2 mV on any of VDD/RESETn/POR_RAW/IBIAS, or 1 ms anchor); the transition counts are re-derived from the stored trace and compared with the full-resolution result per point (`stored_trace.agrees_with_full_resolution`).",
            },
            "requests": res["requests"],
            "points": pts,
            "pairs": pairs,
            "summary": summarize(pts),
            "crosscheck": xc,
            "absent_coverage": ABSENT,
            "follow_on": follow,
            "links": {
                "testbench": "sim/supply-ramp-top/testbench/tb_temp_por_ramp.sch",
                "manifest": "sim/supply-ramp-top/experiment.json",
                "driver": "sim/supply-ramp-top/run_ramp_campaign.py",
                "checker": "sim/supply-ramp-top/ramp_checker.py",
                "netlist_snapshots": f"sim/supply-ramp-top/netlist-snapshots/{record_id}/",
                "corners_dir": f"sim/supply-ramp-top/corners/{record_id}/",
                "json": f"sim/supply-ramp-top/records/{record_id}.json",
                "record": f"sim/supply-ramp-top/records/{record_id}.md",
            },
        }
        rec_dir.mkdir(parents=True, exist_ok=True)
        (rec_dir / f"{record_id}.json").write_text(json.dumps(record, indent=1, sort_keys=True, default=float) + "\n")
        (rec_dir / f"{record_id}.md").write_text(render_md(record))
        out_ids.append(record_id)
        print(f"record {variant}: {record_id}  ({n_wave}/{len(pts)} with waveform)")
    return 0


# --------------------------------------------------------------------------
# selftest
# --------------------------------------------------------------------------


def cmd_selftest(args) -> int:
    git_info = cr.git_state()
    now = datetime.now(timezone.utc)
    record_id = f"{now:%Y%m%d}-{now:%H%M%S}-{git_info['sha']}-checker-selftest"
    results = rc.run_selftest(HERE / "selftest")
    # the committed double-release fixture is re-read from disk and re-graded: the on-disk waveform is the evidence
    fixture = HERE / "selftest" / "double_release.wave.json"
    again = rc.analyze(rc.load_wave(fixture), 3.3, 1e4)
    ok = all(r["ok"] for r in results) and again["resetn"]["n_release"] == 2 and "repeated_release" in again["fail_codes"]
    rec_dir = HERE / "records"
    rec_dir.mkdir(exist_ok=True)
    if (rec_dir / f"{record_id}.md").exists():
        raise SystemExit("record exists")
    doc = {
        "record_id": record_id,
        "timestamp": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "author": args.author or cr.default_author(),
        "supersedes": args.supersedes,
        "kind": "transition-checker self-test (controlled waveforms, no simulation)",
        "git": git_info,
        "cases": results,
        "double_release_fixture": {"path": "sim/supply-ramp-top/selftest/double_release.wave.json", "regraded_from_disk": {"verdict": again["verdict"], "n_release": again["resetn"]["n_release"], "n_reassert": again["resetn"]["n_reassert"], "fail_codes": again["fail_codes"]}},
        "overall_pass": ok,
    }
    (rec_dir / f"{record_id}.json").write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n")
    L = [f"# Record {record_id}", "", f"- **Record ID**: {record_id}", "- **Experiment**: `supply-ramp-top` -- transition-checker self-test",
         "- **Claim**: proves `ramp_checker.py` detects the failure modes the campaign grades -- including a SECOND RELEASE -- on controlled synthetic waveforms with known answers (a clean single release must PASS, so the checker is not vacuous). No simulation is involved; the campaign records use the same code.",
         f"- **Repo state**: `{git_info['sha']}` on `{git_info['branch']}`" + (" (working tree dirty at run time)" if git_info["dirty"] else " (clean working tree)"),
         "- **Netlist provenance**: synthetic waveforms (klt waveform-JSON shape), generated by `ramp_checker.selftest_cases()`; the single-release and double-release waveforms are committed under `sim/supply-ramp-top/selftest/`.",
         "", "| case | expected | got | failure codes | releases | re-asserts | ok |", "|---|---|---|---|---|---|---|"]
    for r in results:
        L.append(f"| {r['case']} | {r['expected_verdict']} | {r['verdict']} | {', '.join(r['fail_codes']) or '-'} | {r['n_release']} | {r['n_reassert']} | {'yes' if r['ok'] else 'NO'} |")
    d = doc["double_release_fixture"]["regraded_from_disk"]
    L += ["", f"The committed double-release waveform, re-read from disk and re-graded: verdict **{d['verdict']}**, {d['n_release']} releases, {d['n_reassert']} re-assert, codes {d['fail_codes']}.",
          "", f"**Overall: {'PASS' if ok else 'FAIL'}**", "", f"- **Timestamp / author**: {doc['timestamp']}, {doc['author']}", f"- **Supersedes**: {args.supersedes or '(none)'}", "",
          "Written by `sim/supply-ramp-top/run_ramp_campaign.py selftest`. Append-only.", ""]
    (rec_dir / f"{record_id}.md").write_text("\n".join(L))
    print(f"selftest record {record_id}: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 2


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--variant", action="append", choices=["as-drawn", "diag-mn1-l20"])
    r.add_argument("--jobs", type=int, default=2, help="concurrent fleet submissions (max 2)")
    r.add_argument("--run-id")
    r.add_argument("--retry-failed", action="store_true", help="re-submit only requests with no usable report (fleet capacity refusals etc.); earlier attempts are archived")
    r.add_argument("--capacity-wait", type=float, default=0, help="batch.capacity_wait_s: seconds to wait out a Spot/fleet capacity refusal")
    x = sub.add_parser("crosscheck")
    x.add_argument("--run-id", required=True)
    c = sub.add_parser("record")
    c.add_argument("--run-id", required=True)
    c.add_argument("--variant", action="append", choices=["as-drawn", "diag-mn1-l20"])
    c.add_argument("--follow-on-file")
    c.add_argument("--author")
    c.add_argument("--supersedes")
    s = sub.add_parser("selftest")
    s.add_argument("--author")
    s.add_argument("--supersedes")
    args = ap.parse_args(argv)
    return {"run": cmd_run, "crosscheck": cmd_crosscheck, "record": cmd_record, "selftest": cmd_selftest}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
