#!/usr/bin/env python3
"""Focused diagnosis of the two RESETn re-assertions in the as-drawn supply-ramp campaign (issue #142).

Source campaign: record 20261010-015905-fbd6329 (issue #101), where exactly two of 360 points released
RESETn once and then re-asserted it:

    A  ss, -40 C, 3.63 V, 500 kV/s        B  fs, 27 C, 2.97 V, 5 kV/s

Question: are these design-level behaviour of the RESETn -> temp_core.EN -> shared IBIAS -> POR_RAW loop,
or an artifact of the simulator landing on the nonphysical temp_core branch (issue #86)?

The matrix is declared in experiment.json (``reassert_diagnosis``).  Every case is ONE single-corner
``klt sim --backend batch`` request on the UNCHANGED assembled netlist (same testbench, same
design/netlist/temp_por_top.spice, nothing replaced by an ideal source).  The only deck additions are
extra ``.save`` cards (internal nodes for event ordering) and, for solver discriminators, a trailing
``.options`` card / a different ``tmax``.  This script never launches ngspice over the matrix and never
falls back to local runs: a refused / failed case is a recorded outcome.

Stages:  matrix | run | record
"""

from __future__ import annotations

import argparse
import concurrent.futures
import gzip
import json
import math
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import ramp_checker as rc  # noqa: E402
import run_ramp_campaign as camp  # noqa: E402

sim_common = camp.sim_common
cr = camp.cr
SLUG = camp.SLUG
MANIFEST = camp.MANIFEST
BUILD = camp.BUILD
say = camp.say
SOURCE_RECORD = "20261010-015905-fbd6329"

EXTRA_SAVES = [
    "v(xdut.xcmp.cmpo)", "v(xdut.xcmp.n1)", "v(xdut.xcmp.sns)", "v(xdut.xcmp.snsb)", "v(xdut.xcmp.tn)",
    "v(xdut.xpor.pdn)", "v(xdut.xpor.ndl)", "v(xdut.xpor.ndg)", "v(xdut.xpor.pgdg)", "v(xdut.xpor.pgdgb)",
    "v(xdut.xpor.tim)", "v(xdut.xpor.nd1)", "v(xdut.xpor.trip)", "v(xdut.xpor.rstb)",
]
# nodes that enter the event-order timeline (name -> label); the V_MID crossings of each are ordered
TIMELINE_NODES = [
    "v(resetn)", "v(xdut.por_raw)", "v(xdut.xcmp.cmpo)", "v(xdut.xcmp.n1)", "v(xdut.xpor.ndg)",
    "v(xdut.xpor.pgdg)", "v(xdut.xpor.pgdgb)", "v(xdut.xpor.tim)", "v(xdut.xpor.nd1)",
    "v(xdut.xpor.trip)", "v(xdut.xpor.rstb)", "v(xdut.xpor.pdn)", "v(xdut.xpor.ndl)",
]
TRACE_COLS = (
    "time", "v(vdd)", "v(resetn)", "v(xdut.por_raw)", "v(xdut.ibias)", "i(bvdd)", "v(ptat)", "v(ctat)",
    "v(xdut.vref)", "v(xdut.bias_ok)", "v(xdut.xbias.na)", "v(xdut.xbias.nb)", "v(xdut.xbias.pb)", "v(xdut.xbias.pg)",
    "v(xdut.xtemp.na)", "v(xdut.xtemp.nb)", *EXTRA_SAVES,
)
TRACE_DV = 5e-3
TRACE_DT = 1e-3
REL_SPREAD_TOL = 0.05  # physical-branch release-time agreement (fraction); a measurement definition, not a bound


# --------------------------------------------------------------------------
# matrix
# --------------------------------------------------------------------------


def case_id(point: str, variant: str, rate: float) -> str:
    return f"{point}__{variant}__{sim_common.rate_tag(rate)}"


def build_matrix(man: dict) -> list[dict]:
    d = man["reassert_diagnosis"]
    cases = []
    for pname, pt in d["points"].items():
        for vname in d["solver_variants_at_exact_rate"]:
            cases.append({"point": pname, "variant": vname, "rate": pt["rate_v_per_s"], "role": "exact" if vname == "base" else "solver"})
        for rate in pt["adjacent_rates_v_per_s"]:
            for vname in d["adjacent_rate_variants"]:
                cases.append({"point": pname, "variant": vname, "rate": rate, "role": "adjacent-rate"})
    for c in cases:
        c["id"] = case_id(c["point"], c["variant"], c["rate"])
    ids = [c["id"] for c in cases]
    assert len(ids) == len(set(ids)), "duplicate matrix case"
    return cases


def netlist_for(head: str, man: dict, case: dict) -> str:
    d = man["reassert_diagnosis"]
    v = d["variants"][case["variant"]]
    base = camp.build_netlist(head, {"netlist_edit": None}, case["rate"])
    marker = "\n* temp_por_top -- generated by design/netlist.py"
    if base.count(marker) != 1:
        raise SystemExit("cannot locate the DUT splice point in the generated netlist")
    pre, post = base.split(marker)
    extra = ["", f"* ---- issue #142 diagnostic additions (case {case['id']}); circuit untouched ----",
             ".save " + " ".join(EXTRA_SAVES[:7]), ".save " + " ".join(EXTRA_SAVES[7:])]
    if v.get("options"):
        extra.append(f".options {v['options']}")
    return pre + "\n".join(extra) + "\n" + marker + post


def request_for(man: dict, case: dict, backend: str = "batch") -> dict:
    d = man["reassert_diagnosis"]
    pt = d["points"][case["point"]]
    v = d["variants"][case["variant"]]
    req = camp.build_request("netlist.spice", case["rate"], man, backend)
    req["corners"] = {"process": [pt["process"]], "supply_v": {"vset": [pt["supply_v"]]}, "temperature_c": [pt["temperature_c"]]}
    tstop = camp.tstop_for(case["rate"])
    tmax = v.get("tmax_s", camp.TMAX_S)
    req["analysis"] = {"kind": "tran", "args": f"1u {tstop:.9g} 0 {tmax:.3g}"}
    req["options"]["timeout_s"] = 2400
    return req


# --------------------------------------------------------------------------
# run
# --------------------------------------------------------------------------


def cmd_matrix(args) -> int:
    man = sim_common.load_manifest(MANIFEST)
    for c in build_matrix(man):
        print(f"{c['id']:40s} {c['role']:14s} rate={c['rate']:g}")
    return 0


def submit_case(case, head, man, run_dir):
    d = run_dir / case["id"]
    netlist = netlist_for(head, man, case)
    req = request_for(man, case)
    d.mkdir(parents=True, exist_ok=True)
    if (d / "report.json").is_file():
        n = 1
        while (d / f"attempt{n}").exists():
            n += 1
        (d / f"attempt{n}").mkdir()
        for name in ("report.json", "klt.stderr"):
            if (d / name).is_file():
                shutil.move(str(d / name), str(d / f"attempt{n}" / name))
    (d / "netlist.spice").write_text(netlist)
    (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
    say(f"[submit] {case['id']} -> batch fleet")
    p = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "batch", "-o", str(d / "out"), "--format", "json"],
                       capture_output=True, text=True, timeout=4 * 3600)
    (d / "report.json").write_text(p.stdout)
    (d / "klt.stderr").write_text(p.stderr)
    try:
        st = json.loads(p.stdout).get("status", "?")
    except json.JSONDecodeError:
        st = "NO-JSON"
    say(f"[done]   {case['id']}: exit {p.returncode}, status {st}")
    return {"case": case["id"], "exit": p.returncode, "status": st}


def cmd_run(args) -> int:
    man = sim_common.load_manifest(MANIFEST)
    pdk = cr.resolve_pdk(cr.load_pin())
    git_info = cr.git_state()
    if git_info["dirty"] and not args.allow_dirty:
        raise SystemExit("working tree is dirty: commit (and push) first so the fleet source SHA resolves")
    now = datetime.now(timezone.utc)
    run_id = args.run_id or f"{now:%Y%m%d-%H%M%S}-{git_info['sha']}"
    run_dir = BUILD / run_id
    retry = args.retry_failed
    if retry:
        if not run_dir.exists():
            raise SystemExit(f"{run_dir} does not exist")
    else:
        if run_dir.exists():
            raise SystemExit(f"{run_dir} exists")
        run_dir.mkdir(parents=True)
    head = camp.tb_netlist_head(run_dir / ("retry" if retry else "."), pdk)
    cases = build_matrix(man)
    if args.only:
        cases = [c for c in cases if c["id"] in args.only]
    if retry:
        cases = [c for c in cases if not sim_common.report_usable(run_dir / c["id"] / "report.json")]
        say(f"retrying {len(cases)} case(s) without a usable report")
    meta = {"run_id": run_id, "started_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"), "git": git_info,
            "klt_client": sim_common.klt_version(), "klt_sim_backend_env": os.environ.get("KLT_SIM_BACKEND"),
            "cases": [c["id"] for c in cases]}
    mp = run_dir / "run.json"
    if retry:
        old = json.loads(mp.read_text())
        old.setdefault("retries", []).append({"at_utc": meta["started_utc"], "git": git_info, "cases": meta["cases"]})
        meta = old
    else:
        mp.write_text(json.dumps(meta, indent=2) + "\n")
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, args.jobs)) as ex:
        futs = [ex.submit(submit_case, c, head, man, run_dir) for c in cases]
        for c, f in zip(cases, futs):
            try:
                results.append(f.result())
            except Exception as err:  # noqa: BLE001 -- recorded
                results.append({"case": c["id"], "error": repr(err)})
                say(f"[error] {c['id']}: {err!r}")
    key = "retry_results" if retry else "submit_results"
    meta.setdefault(key, [])
    meta[key] = (meta[key] + results) if retry else results
    mp.write_text(json.dumps(meta, indent=2) + "\n")
    print(f"raw outputs: {run_dir}")
    return 0


# --------------------------------------------------------------------------
# grading and event order
# --------------------------------------------------------------------------


def first_violation(w, vf):
    """Per saved node: time of the first sample (t>0) outside [PHYS_LO, vf+PHYS_HI_MARGIN]."""
    hi = vf + rc.PHYS_HI_MARGIN
    t = w["time"]
    out = {}
    for name in rc.PHYS_NODES + tuple(EXTRA_SAVES):
        col = w.get(name)
        if col is None:
            continue
        for tt, x in zip(t, col):
            if tt > 0 and not (rc.PHYS_LO <= x <= hi):
                out[name] = {"t_s": tt, "v": x}
                break
    return out


def timeline(w, vf, res, window=200e-6):
    """Event order around each RESETn transition from the full-resolution trace (no inference)."""
    t = w["time"]
    v_mid = rc.FRAC_MID * vf
    rst = w["v(resetn)"]
    rel, fall = rc.schmitt(t, rst, rc.FRAC_IL * vf, rc.FRAC_IH * vf)
    ev = []
    for node in TIMELINE_NODES:
        col = w.get(node)
        if col is None:
            continue
        for d in ("rise", "fall"):
            for tc in rc.crossings(t, col, v_mid, d):
                ev.append({"t_s": tc, "node": node, "event": f"V_MID {d}"})
    viol_all = first_violation(w, vf)
    for node, vv in viol_all.items():
        ev.append({"t_s": vv["t_s"], "node": node, "event": f"FIRST out-of-window sample ({vv['v']:.3g} V)"})
    for tc in rel:
        ev.append({"t_s": tc, "node": "v(resetn)", "event": "RELEASE (V_IH rise)"})
    for tc in fall:
        ev.append({"t_s": tc, "node": "v(resetn)", "event": "RE-ASSERT (V_IL fall)"})
    ev.sort(key=lambda e: e["t_s"])
    out = {"anchors": [], "viol": viol_all}
    anchors = [("release", x) for x in rel] + [("reassert", x) for x in fall]
    for kind, ta in sorted(anchors, key=lambda a: a[1]):
        win = [e for e in ev if ta - window <= e["t_s"] <= ta + window]
        out["anchors"].append({
            "kind": kind, "t_s": ta,
            "ibias_v": {off: rc.interp_at(t, w["v(xdut.ibias)"], ta + off) for off in (-200e-6, -20e-6, 0.0, 20e-6, 200e-6)},
            "events_pm_200us": win,
        })
    # supply-current sign change (physicality onset by current) and PTAT/CTAT excursion onset are in 'viol'
    isup = [-x for x in w["i(bvdd)"]]
    first_neg = next((tt for tt, x in zip(t, isup) if tt > 0 and x < 0), None)
    out["first_negative_isup_s"] = first_neg
    return out


TRIGGER_COLS = ("v(vdd)", "v(resetn)", "v(xdut.por_raw)", "v(xdut.ibias)", "v(ptat)", "v(ctat)")
WINDOW_S = 100e-6  # every sample within +-WINDOW_S of a RESETn release/re-assert is kept (all columns)


def compress_ext(w, vf):
    names = [c for c in TRACE_COLS if c in w]
    cols = [w[c] for c in names]
    t = w["time"]
    n = len(t)
    rel, fall = rc.schmitt(t, w["v(resetn)"], rc.FRAC_IL * vf, rc.FRAC_IH * vf)
    anchors = rel + fall
    trig = [names.index(c) for c in TRIGGER_COLS if c in names]
    rows = [[c[0] for c in cols]]
    last = rows[0]
    for i in range(1, n - 1):
        cur = [c[i] for c in cols]
        in_win = any(abs(t[i] - a) <= WINDOW_S for a in anchors)
        if in_win or cur[0] - last[0] >= TRACE_DT or any(abs(cur[k] - last[k]) >= TRACE_DV for k in trig):
            rows.append(cur)
            last = cur
    rows.append([c[n - 1] for c in cols])
    return names, rows


def write_ext_trace(path, names, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# {','.join(names)}  (change-triggered: dV>={TRACE_DV * 1e3:g} mV on vdd/resetn/por_raw/ibias/ptat/ctat or dt>={TRACE_DT * 1e3:g} ms; every sample within +-100 us of a RESETn release/re-assert is kept)"]
    lines += [",".join(f"{x:.6g}" for x in r) for r in rows]
    with gzip.open(path, "wt", compresslevel=9) as fh:
        fh.write("\n".join(lines) + "\n")


def classify(res):
    """Per-run flags used by the verdict rules."""
    if res is None or "resetn" not in res:
        return {"usable": False}
    rs = res["resetn"]
    return {
        "usable": True,
        "physical": res["physical"]["ok"],
        "resolved": res["resolution_ok"] and res["ramp_ok"],
        "reasserts": rs["n_reassert"] > 0 or rs["n_release"] > 1 or rs["n_runt"] > 0,
        "n_release": rs["n_release"],
        "n_reassert": rs["n_reassert"],
        "t_release_s": rs["t_release_s"],
    }


def verdict_for_point(runs):
    """Strict rules from issue #142.

    design-level  : re-assertion (or repeated release / runt) on a run that is physical AND resolved.
    artifact      : at least one run exhibits the re-assertion on a NONphysical branch, AND at least
                    two physical+resolved runs at the exact rate (different solver settings) show a
                    single clean release with release times within REL_SPREAD_TOL of each other, AND
                    no physical+resolved run anywhere in this point's matrix (adjacent-rate
                    controls included) re-asserts.
    unresolved    : anything else.
    """
    flags = {r["id"]: classify(r.get("check")) for r in runs}
    good = [r for r in runs if flags[r["id"]].get("usable") and flags[r["id"]]["physical"] and flags[r["id"]]["resolved"]]
    design = [r["id"] for r in good if flags[r["id"]]["reasserts"]]
    if design:
        return "physical design-level re-assertion", f"re-assertion on physical, resolved run(s): {', '.join(design)}", flags
    exhibits = [r["id"] for r in runs if flags[r["id"]].get("usable") and flags[r["id"]]["reasserts"] and not flags[r["id"]]["physical"]]
    exact_good = [r for r in good if r["role"] in ("exact", "solver") and flags[r["id"]]["n_release"] == 1 and flags[r["id"]]["n_reassert"] == 0]
    if not exhibits:
        return "unresolved", "no run in this matrix reproduced the re-assertion (not even the original case), so there is no re-assertion whose disappearance could be shown", flags
    if len(exact_good) < 2:
        return "unresolved", f"re-assertion exhibited on a nonphysical branch ({', '.join(exhibits)}) but fewer than two physical+resolved single-release runs at the exact rate ({len(exact_good)}), so physical-branch stability is not demonstrated", flags
    tr = [flags[r["id"]]["t_release_s"] for r in exact_good]
    spread = (max(tr) - min(tr)) / (sum(tr) / len(tr))
    if spread > REL_SPREAD_TOL:
        return "unresolved", f"physical-branch release times disagree by {spread:.1%} (> {REL_SPREAD_TOL:.0%}) across {', '.join(r['id'] for r in exact_good)}", flags
    return "solver/nonphysical artifact", (
        f"re-assertion exhibited only on nonphysical run(s) {', '.join(exhibits)}; {len(exact_good)} physical+resolved exact-rate runs "
        f"({', '.join(r['id'] for r in exact_good)}) show one clean release with release-time spread {spread:.2%}; "
        "no physical+resolved run in the matrix re-asserts"), flags


def load_case(case, run_dir, man, corners_dir, write):
    d = run_dir / case["id"]
    rec = dict(case)
    rec.update({"tstop_s": camp.tstop_for(case["rate"])})
    rp = d / "report.json"
    attempts = []
    for ad in sorted(d.glob("attempt*")):
        try:
            body = json.loads((ad / "report.json").read_text()) if (ad / "report.json").is_file() else {}
            msg = (body.get("error") or {}).get("message") or ("report status " + str(body.get("status")))
        except json.JSONDecodeError:
            msg = "unparseable report"
        attempts.append(camp.scrub(msg, run_dir)[:400])
    if attempts:
        rec["failed_earlier_attempts"] = attempts
    if not rp.is_file():
        rec["outcome"] = "NOT SUBMITTED"
        rec["check"] = None
        return rec
    try:
        rep = json.loads(rp.read_text())
    except json.JSONDecodeError:
        rec["outcome"] = "NO JSON from klt: " + camp.scrub((d / "klt.stderr").read_text()[-500:], run_dir)
        rec["check"] = None
        return rec
    if "corners" not in rep:
        rec["outcome"] = "klt error (no corners reported): " + camp.scrub(str((rep.get("error") or {}).get("message", rep))[:500], run_dir)
        rec["check"] = None
        return rec
    remote = (rep.get("environment") or {}).get("remote") or {}
    rec.update({"job_id": remote.get("job_id"), "state": remote.get("state"), "instance_type": remote.get("instance_type"),
                "lifecycle": remote.get("lifecycle"), "runner_klt_version": remote.get("runner_klt_version"),
                "elapsed_seconds": remote.get("elapsed_seconds"), "klt_status": rep.get("status")})
    pt = man["reassert_diagnosis"]["points"][case["point"]]
    vf = pt["supply_v"]
    c = (rep.get("corners") or [None])[0]
    rec["diagnostics"] = [{"severity": g.get("severity"), "code": g.get("code"), "message": camp.scrub(g.get("message", ""), run_dir)[:300]} for g in (c or {}).get("diagnostics", [])]
    rec["runtime_s"] = (c or {}).get("runtime_s")
    art = (c or {}).get("artifacts") or {}
    wp = Path(art["waveform"]) if art.get("waveform") else None
    if wp is None or not wp.is_file():
        rec["outcome"] = "ERROR (no waveform retrieved)"
        rec["check"] = None
        return rec
    w = rc.load_wave(wp)
    res = rc.analyze(w, vf, case["rate"])
    rec["check"] = res
    rec["outcome"] = res["verdict"]
    if "resetn" in res:
        rows = rc.compress(w)
        st = rc.transitions_from_stored(rows, vf)
        res["stored_trace"] = {
            "rows": len(rows), "full_samples": len(w["time"]), "n_release": st["n_release"], "n_reassert": st["n_reassert"],
            "n_runt": st["n_runt"], "premature": st["premature"],
            "agrees_with_full_resolution": (st["n_release"] == res["resetn"]["n_release"] and st["n_reassert"] == res["resetn"]["n_reassert"]
                                            and st["n_runt"] == res["resetn"]["n_runt"] and st["premature"] == res["resetn"]["premature"]),
        }
        rec["timeline"] = timeline(w, vf, res)
        rec["missing_extra_saves"] = [n for n in EXTRA_SAVES if n not in w]
        if write:
            names, erows = compress_ext(w, vf)
            write_ext_trace(corners_dir / f"{case['id']}.trace.csv.gz", names, erows)
            rec["trace_file"] = f"{case['id']}.trace.csv.gz"
            rec["trace_rows"] = len(erows)
            art_log = Path(art["log"]).read_text() if art.get("log") and Path(art["log"]).is_file() else "(no log)"
            (corners_dir / f"{case['id']}.log").write_text(camp.scrub(art_log, run_dir))
    return rec


def fmt(x, spec=".4g"):
    return "n/a" if x is None else f"{x:{spec}}"


def render_md(rec):
    L = [f"# Record {rec['record_id']}", "",
         f"- **Record ID**: {rec['record_id']}",
         f"- **Experiment**: `supply-ramp-top` -- re-assertion diagnosis (issue #142); cites source record `{SOURCE_RECORD}`",
         "- **Claim**: " + rec["claim"],
         f"- **Netlist provenance**: schematic (`sim/supply-ramp-top/testbench/tb_temp_por_ramp.sch`, DUT `design/netlist/temp_por_top.spice`, unchanged); decks under `netlist-snapshots/{rec['record_id']}/`",
         f"- **PDK**: sky130A @ open_pdks `{rec['pdk']['installed_commit']}` (matches pin: {rec['pdk']['matches_pin']})",
         f"- **Tools**: klt client `{rec['tools']['klt_client']}`; fleet runner klt `{rec['tools']['fleet_runner_klt']}`, `{rec['tools']['fleet_ngspice']}`; backend batch (explicit `--backend batch`; `KLT_SIM_BACKEND={rec['tools']['klt_sim_backend_env']}`)",
         f"- **Repo state**: `{rec['git']['sha']}` on `{rec['git']['branch']}` ({'DIRTY' if rec['git']['dirty'] else 'clean working tree'}); run id `{rec['run_id']}`",
         "- **Statistical convention**: N/A (diagnostic cases, not a distribution claim)",
         "- **Status**: EXPLORATORY. No ratified ramp envelope exists (DR-003 Sec8); nothing here is a spec claim, no gf180 numeric limit is used, `spec/` and circuit geometry are untouched.", "",
         "## Matrix (all declared cases, none dropped)", "",
         "| case | role | point | rate (V/s) | variant | outcome | job id | state |", "|---|---|---|---|---|---|---|---|"]
    for r in rec["cases"]:
        L.append(f"| {r['id']} | {r['role']} | {r['point']} | {r['rate']:g} | {r['variant']} | {str(r['outcome'])[:90]} | {r.get('job_id')} | {r.get('state')} |")
    L += ["", "Variants:", ""]
    for k, v in rec["variants"].items():
        L.append(f"- `{k}`: {v['description']}")
    L += ["", "## Per-case grading (full-resolution waveforms)", "",
          "| case | physical | resolved | n_rel | n_re | t_rel (ms) | POR_RAW rises/falls | IBIAS step (mV) | settled isup (A) | first nonphys. node (t ms) | first isup<0 (ms) | stored trace agrees |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rec["cases"]:
        c = r.get("check")
        if not c or "resetn" not in c:
            L.append(f"| {r['id']} | - | - | - | - | - | - | - | - | - | - | - |")
            continue
        tl = r["timeline"]
        viol = tl["viol"]
        fv = min(viol.items(), key=lambda kv: kv[1]["t_s"]) if viol else None
        L.append(
            f"| {r['id']} | {'ok' if c['physical']['ok'] else 'NONPHYSICAL'} | {'yes' if c['resolution_ok'] and c['ramp_ok'] else 'NO'} | {c['resetn']['n_release']} | {c['resetn']['n_reassert']} | "
            f"{fmt(c['resetn']['t_release_s'] and c['resetn']['t_release_s'] * 1e3)} | {c['por_raw']['n_rise']}/{c['por_raw']['n_fall']} | "
            f"{fmt(c['ibias']['release_step_v'] and c['ibias']['release_step_v'] * 1e3, '.3g')} | {c['physical']['isup_end_a']:.3g} | "
            f"{(fv[0] + ' @ ' + format(fv[1]['t_s'] * 1e3, '.4g')) if fv else '-'} | {fmt(tl['first_negative_isup_s'] and tl['first_negative_isup_s'] * 1e3)} | {c['stored_trace']['agrees_with_full_resolution']} |")
    L += ["", "## Event order around RESETn transitions (measured from the trace)", "",
          "Each line is a V_MID crossing (0.5 x final supply) of the listed internal node within +-200 us of a RESETn release / re-assert, in time order. Only listed, measured orderings are claimed; any mechanism beyond them is UNVERIFIED."]
    for r in rec["cases"]:
        c = r.get("check")
        if not c or "resetn" not in c or not r["timeline"]["anchors"]:
            continue
        if not (c["resetn"]["n_reassert"] or c["resetn"]["n_release"] > 1) and r["role"] != "exact":
            continue
        L += ["", f"### {r['id']}"]
        for a in r["timeline"]["anchors"]:
            L.append(f"- **{a['kind']}** at {a['t_s'] * 1e3:.5g} ms; IBIAS (V) at t{{-200,-20,0,+20,+200}} us = " + ", ".join(f"{v:.4g}" for v in a["ibias_v"].values()))
            for e in a["events_pm_200us"]:
                L.append(f"  - {e['t_s'] * 1e3:.6g} ms  {e['node']}  {e['event']}")
        viol = r["timeline"]["viol"]
        if viol:
            L.append("- first out-of-window sample per node: " + "; ".join(f"{k} @ {v['t_s'] * 1e3:.4g} ms ({v['v']:.3g} V)" for k, v in sorted(viol.items(), key=lambda kv: kv[1]["t_s"])))
    L += ["", "## Per-point verdicts", ""]
    for pname, v in rec["verdicts"].items():
        L += [f"### {pname}: **{v['verdict']}**", "", v["basis"], ""]
    L += ["Verdict rules (issue #142, applied mechanically by `run_reassert_diagnosis.py`):", "",
          "- `physical design-level re-assertion`: a re-assertion (or repeated release / runt) on a run that passes both the physicality guard and the resolution guard.",
          f"- `solver/nonphysical artifact`: re-assertion appears only on nonphysical run(s); at least two physical+resolved exact-rate runs show one clean release agreeing within {REL_SPREAD_TOL:.0%}; no physical+resolved run in the point's matrix (adjacent rates included) re-asserts.",
          "- `unresolved`: anything else.", ""]
    L += ["## Absent coverage (stated, not hidden)"]
    for a in rec["absent_coverage"]:
        L.append(f"- {a}")
    L += ["", "## Links", ""]
    for k, v in rec["links"].items():
        L.append(f"- {k}: `{v}`")
    L += [f"- **Timestamp / author**: {rec['timestamp']}, {rec['author']}", f"- **Supersedes**: {rec['supersedes'] or '(none; cites ' + SOURCE_RECORD + ', which is unchanged)'}", "",
          "Written by `sim/supply-ramp-top/run_reassert_diagnosis.py`. Append-only: never edit this file -- a correction is a new record with a `Supersedes` field.", ""]
    return "\n".join(L)


def cmd_record(args) -> int:
    man = sim_common.load_manifest(MANIFEST)
    run_dir = BUILD / args.run_id
    meta = json.loads((run_dir / "run.json").read_text())
    pin = cr.load_pin()
    pdk = cr.resolve_pdk(pin)
    git_info = cr.git_state()
    if git_info["dirty"]:
        raise SystemExit("working tree is dirty: commit the driver/manifest before recording")
    now = datetime.now(timezone.utc)
    record_id = f"{now:%Y%m%d-%H%M%S}-{git_info['sha']}-reassert-diagnosis"
    rec_dir = HERE / "records"
    corners_dir = HERE / "corners" / record_id
    snap_dir = HERE / "netlist-snapshots" / record_id
    for p in (rec_dir / f"{record_id}.md", rec_dir / f"{record_id}.json", corners_dir, snap_dir):
        if p.exists():
            raise SystemExit(f"{p} exists -- append-only")
    cases = [load_case(c, run_dir, man, corners_dir, True) for c in build_matrix(man)]
    snap_dir.mkdir(parents=True, exist_ok=True)
    corners_dir.mkdir(parents=True, exist_ok=True)
    for c in cases:
        d = run_dir / c["id"]
        if (d / "netlist.spice").is_file():
            shutil.copyfile(d / "netlist.spice", snap_dir / f"{c['id']}.spice")
            shutil.copyfile(d / "request.json", snap_dir / f"{c['id']}.request.json")
        if (d / "report.json").is_file():
            (corners_dir / f"{c['id']}.klt-report.json").write_text(camp.scrub((d / "report.json").read_text(), run_dir))
    verdicts = {}
    for pname in man["reassert_diagnosis"]["points"]:
        runs = [c for c in cases if c["point"] == pname]
        v, basis, flags = verdict_for_point(runs)
        verdicts[pname] = {"verdict": v, "basis": basis, "per_case_flags": flags}
    ngs = sorted({x for c in cases for x in [c.get("runner_klt_version")] if x})
    d = man["reassert_diagnosis"]
    record = {
        "record_id": record_id, "run_id": args.run_id, "timestamp": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "author": args.author or cr.default_author(), "supersedes": args.supersedes, "cites": SOURCE_RECORD,
        "claim": d["claim"], "git": git_info,
        "pdk": {"variant": pdk.variant, "installed_commit": pdk.installed_commit, "pinned_commit": pin["open_pdks_commit"], "matches_pin": pdk.matches_pin},
        "tools": {"klt_client": meta["klt_client"], "fleet_runner_klt": ", ".join(ngs) or "unknown", "fleet_ngspice": "ngspice-46 (per fleet log)",
                  "klt_sim_backend_env": meta.get("klt_sim_backend_env"), "python": cr.tool_versions()["python"], "platform": cr.tool_versions()["platform"]},
        "run_meta": meta, "variants": d["variants"], "points": d["points"],
        "cases": cases, "verdicts": verdicts,
        "absent_coverage": d["absent_coverage"],
        "links": {"manifest": "sim/supply-ramp-top/experiment.json", "driver": "sim/supply-ramp-top/run_reassert_diagnosis.py",
                  "source_record": f"sim/supply-ramp-top/records/{SOURCE_RECORD}.md",
                  "netlist_snapshots": f"sim/supply-ramp-top/netlist-snapshots/{record_id}/", "corners_dir": f"sim/supply-ramp-top/corners/{record_id}/",
                  "json": f"sim/supply-ramp-top/records/{record_id}.json", "record": f"sim/supply-ramp-top/records/{record_id}.md"},
    }
    (rec_dir / f"{record_id}.json").write_text(json.dumps(record, indent=1, sort_keys=True, default=float) + "\n")
    (rec_dir / f"{record_id}.md").write_text(render_md(record))
    print(f"record {record_id}")
    for k, v in verdicts.items():
        print(f"  {k}: {v['verdict']} -- {v['basis']}")
    return 0


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("matrix")
    r = sub.add_parser("run")
    r.add_argument("--jobs", type=int, default=2)
    r.add_argument("--run-id")
    r.add_argument("--retry-failed", action="store_true")
    r.add_argument("--only", action="append")
    r.add_argument("--allow-dirty", action="store_true")
    c = sub.add_parser("record")
    c.add_argument("--run-id", required=True)
    c.add_argument("--author")
    c.add_argument("--supersedes")
    a = ap.parse_args(argv)
    return {"matrix": cmd_matrix, "run": cmd_run, "record": cmd_record}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
