#!/usr/bin/env python3
"""Driver for the assembled temp_por_top Iq campaign (issue #107).

The 45-point PVT grid, per state, is expressed as ONE ``klt sim`` corner
request per state (process x supply x temperature are klt's own corner axes)
and goes to the Spot batch fleet with an explicit ``--backend batch``; this
script never launches ngspice over the grid itself, and there is no local
fallback for the grid if the fleet refuses (the refusal is recorded).

Stages (each a subcommand):

  run         build the two generated decks + requests and submit them to the fleet.
  crosscheck  one single-corner (tt / 27 C / 3.30 V) LOCAL probe per state (``--backend local``).
  record      grade every retrieved waveform with iq_checker.py and write the append-only
              evidence (snapshots, scrubbed klt reports, decimated traces, md + json twins).
  selftest    run the settling/physicality checker on synthetic settled / drifting currents.

States: por-iq (RESETn forced low by a testbench source), iq-total (natural released
state); temp-iq is derived as iq-total - por-iq, labelled incremental.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import functools
import gzip
import json
import os
import re
import statistics
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR / "bin"))
sys.path.insert(0, str(HERE))

import iq_checker as qc  # noqa: E402
import sim_common  # noqa: E402

cr = sim_common.load_corner_run()

SLUG = "iq-top"
MANIFEST = HERE / "experiment.json"
DUT_NETLIST = REPO_ROOT / "design" / "netlist" / "temp_por_top.spice"
BUILD = REPO_ROOT / "sim" / "build" / SLUG
MODEL_LIB = "libs.tech/combined/sky130.lib.spice"
STATES = ["por-iq", "iq-total"]
STATE_TAG = {"por-iq": "por", "iq-total": "total"}

say = sim_common.say
scrub = functools.partial(sim_common.scrub, repo_root=REPO_ROOT)

# the four sub-cell instance lines in the committed top-level export, and the same
# lines with a 0 V ammeter in series with each VDD pin (see experiment.json measurement.attribution_instrumentation)
INSTRUMENT = [
    ("xbias VDD VSS IBIAS VREF BIAS_OK bias_core", "vsbias VDD VDDBIAS 0\nxbias VDDBIAS VSS IBIAS VREF BIAS_OK bias_core"),
    ("xcmp VDD VSS IBIAS VREF BIAS_OK POR_RAW por_comparator", "vscmp VDD VDDCMP 0\nxcmp VDDCMP VSS IBIAS VREF BIAS_OK POR_RAW por_comparator"),
    ("xpor VDD VSS IBIAS POR_RAW RESETn por_output_chain", "vspor VDD VDDPOR 0\nxpor VDDPOR VSS IBIAS POR_RAW RESETn por_output_chain"),
    ("xtemp VDD VSS IBIAS RESETn PTAT CTAT temp_core", "vstemp VDD VDDTEMP 0\nxtemp VDDTEMP VSS IBIAS RESETn PTAT CTAT temp_core"),
]


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def corner_id(proc: str, temp: float, vf: float) -> str:
    return f"{proc}_{cr.fmt_temp(temp)}c_{vf:.2f}v"


def grid(man: dict):
    c = man["corners"]
    return [(p, t, v) for p in c["process"] for t in c["temperature_c"] for v in c["supply_v"]]


# --------------------------------------------------------------------------
# netlists and requests
# --------------------------------------------------------------------------


def tb_netlist_head(state: str, run_dir: Path, pdk) -> str:
    """xschem-netlist the state's testbench; keep only the testbench part (DUT comes from the committed export)."""
    sch = HERE / "testbench" / f"tb_temp_por_iq_{STATE_TAG[state]}.sch"
    produced = cr.netlist_with_xschem(sch, run_dir / "tb" / STATE_TAG[state], pdk)
    text = produced.read_text().replace(str(REPO_ROOT) + os.sep, "")
    head = text.split("\n* expanding")[0]
    return "\n".join(ln for ln in head.splitlines() if ln.strip().lower() != ".end") + "\n"


def instrumented_dut() -> str:
    dut = DUT_NETLIST.read_text()
    dut = "\n".join(ln for ln in dut.splitlines() if ln.strip().lower() != ".end") + "\n"
    for find, repl in INSTRUMENT:
        if dut.count(find) != 1:
            raise SystemExit(f"instrumentation target not found exactly once in {DUT_NETLIST.name}: {find!r}")
        dut = dut.replace(find, repl)
    return dut


def build_netlist(head: str, state: str, man: dict) -> str:
    m = man["measurement"]
    banner = (
        f"* {SLUG} ({state}): generated by sim/iq-top/run_iq_campaign.py -- do not edit\n"
        f"* DUT = design/netlist/temp_por_top.spice with 0 V ammeters in series with each sub-cell VDD pin (attribution only)\n"
        f".param rate={m['rate_v_per_s']:g}\n"
        "* ng_nomodcheck: same setting as sim/spiceinit; carried in the netlist because the\n"
        "* fleet runner ignores options.ngspice_init (see experiment.json ngspice_note)\n"
        ".control\nset ng_nomodcheck\n.endc\n"
    )
    return banner + head + "\n" + instrumented_dut()


def build_request(netlist_name: str, man: dict, backend: str, capacity_wait_s: float = 0) -> dict:
    m = man["measurement"]
    c = man["corners"]
    tw = m["trail_window_s"]
    req = {
        "netlist": netlist_name,
        "backend": backend,
        "models": {"pdk": "sky130A", "lib": MODEL_LIB},
        "corners": {"process": c["process"], "supply_v": {"vset": c["supply_v"]}, "temperature_c": c["temperature_c"]},
        "analysis": {"kind": "tran", "args": f"1u {m['tstop_s']:.9g} 0 {m['tmax_s']:.3g}"},
        "measurements": [
            {"name": "iq_trail_neg", "spice": f".meas tran iq_trail_neg AVG i(bvdd) FROM={tw[0]:.9g} TO={tw[1]:.9g}", "unit": "A"},
            {"name": "vdd_trail", "spice": f".meas tran vdd_trail AVG v(vdd) FROM={tw[0]:.9g} TO={tw[1]:.9g}", "unit": "V"},
            {"name": "resetn_trail", "spice": f".meas tran resetn_trail AVG v(resetn) FROM={tw[0]:.9g} TO={tw[1]:.9g}", "unit": "V"},
        ],
        "options": {"timeout_s": 3000, "keep_artifacts": True, "waveforms": True},
    }
    if backend == "batch":
        req["batch"] = {"runner_version_check": "warn"}
        if capacity_wait_s:
            req["batch"]["capacity_wait_s"] = capacity_wait_s
    return req


def klt_version() -> str:
    p = subprocess.run(["klt", "--version"], capture_output=True, text=True)
    return p.stdout.strip() or p.stderr.strip()


def cmd_run(args) -> int:
    man = load_manifest()
    pdk = cr.resolve_pdk(cr.load_pin())
    git_info = cr.git_state()
    now = datetime.now(timezone.utc)
    run_id = args.run_id or f"{now:%Y%m%d-%H%M%S}-{git_info['sha']}"
    run_dir = BUILD / run_id
    if args.retry_failed:
        if not run_dir.exists():
            raise SystemExit(f"{run_dir} does not exist")
    else:
        if run_dir.exists():
            raise SystemExit(f"{run_dir} exists; refusing to reuse a run id")
        run_dir.mkdir(parents=True)
    states = args.state or STATES
    rate = man["measurement"]["rate_v_per_s"]
    work = list(states)
    if args.retry_failed:
        work = [s for s in states if not sim_common.report_usable(run_dir / s / sim_common.rate_tag(rate) / "report.json")]
        say(f"retrying {len(work)} request(s) without a usable report, capacity_wait_s={args.capacity_wait}")
    heads = {s: tb_netlist_head(s, run_dir if not args.retry_failed else run_dir / "retry", pdk) for s in work}
    meta = {"run_id": run_id, "started_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"), "states": states, "klt_client": klt_version(),
            "klt_sim_backend_env": os.environ.get("KLT_SIM_BACKEND"), "git": git_info}
    if not args.retry_failed:
        (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")

    def one(state):
        req = build_request("netlist.spice", man, "batch", args.capacity_wait)
        return sim_common.submit_request(state, rate, run_dir, build_netlist(heads[state], state, man), req, "", len(grid(man)))

    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, args.jobs)) as ex:
        for f in [ex.submit(one, s) for s in work]:
            try:
                results.append(f.result())
            except Exception as err:  # noqa: BLE001 -- recorded, never swallowed
                results.append({"error": repr(err)})
                say(f"[error] submit raised: {err!r}")
    old = json.loads((run_dir / "run.json").read_text())
    if args.retry_failed:
        old.setdefault("retries", []).append({"at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "capacity_wait_s": args.capacity_wait, "results": results})
    else:
        old["submit_results"] = results
    (run_dir / "run.json").write_text(json.dumps(old, indent=2) + "\n")
    print(f"raw outputs: {run_dir}")
    return 0


def cmd_crosscheck(args) -> int:
    man = load_manifest()
    pdk = cr.resolve_pdk(cr.load_pin())
    run_dir = BUILD / args.run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    for state in args.state or STATES:
        d = run_dir / "crosscheck" / STATE_TAG[state]
        d.mkdir(parents=True, exist_ok=True)
        (d / "netlist.spice").write_text(build_netlist(tb_netlist_head(state, run_dir / "xc", pdk), state, man))
        req = build_request("netlist.spice", man, "local")
        req["corners"] = {"process": ["tt"], "supply_v": {"vset": [3.3]}, "temperature_c": [27]}
        req["options"]["ngspice_init"] = [ln.strip() for ln in (SIM_DIR / "spiceinit").read_text().splitlines() if ln.strip() and not ln.startswith("*")]
        (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
        say(f"[crosscheck] {state}: one local corner (tt/27C/3.30V) on local ngspice")
        p = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "local", "-o", str(d / "out"), "--format", "json"], capture_output=True, text=True, timeout=3600)
        (d / "report.json").write_text(p.stdout)
        (d / "klt.stderr").write_text(p.stderr)
        say(f"[crosscheck] {state}: exit {p.returncode}")
    return 0


# --------------------------------------------------------------------------
# analysis
# --------------------------------------------------------------------------


def decimate(wave: dict, keep: list[str], n: int = 400) -> dict:
    t = wave["time"]
    step = max(1, len(t) // n)
    idx = list(range(0, len(t), step))
    if idx[-1] != len(t) - 1:
        idx.append(len(t) - 1)
    return {"time_s": [t[i] for i in idx], **{k: [wave[k][i] for i in idx] for k in keep if k in wave}}


def classify_failure(corner: dict, log_text: str) -> str:
    if "could not find a valid modelname" in log_text:
        return "model_not_found"
    if "timestep too small" in log_text.lower():
        return "timestep_too_small"
    codes = sorted({d.get("code") for d in corner.get("diagnostics", []) if d.get("code")})
    return "klt:" + ",".join(codes) if codes else "no_waveform"


def analyze_state(state: str, run_dir: Path, man: dict, traces: dict) -> dict:
    rate = man["measurement"]["rate_v_per_s"]
    d = run_dir / state / sim_common.rate_tag(rate)
    rep_path = d / "report.json"
    req = {"state": state}
    pts: dict[str, dict] = {}
    for p, t, v in grid(man):
        pts[corner_id(p, t, v)] = {"id": corner_id(p, t, v), "process": p, "temperature_c": t, "supply_v": v, "status": "nonconverged", "reason": "NOT SUBMITTED / no report"}
    attempts = []
    for ad in sorted(d.glob("attempt*")):
        try:
            body = json.loads((ad / "report.json").read_text()) if (ad / "report.json").is_file() else {}
            msg = (body.get("error") or {}).get("message") or ("report status " + str(body.get("status")))
        except json.JSONDecodeError:
            msg = "unparseable report"
        stderr = (ad / "klt.stderr").read_text()[-400:] if (ad / "klt.stderr").is_file() else ""
        attempts.append(scrub(msg + (" | stderr: " + stderr if stderr.strip() else ""), run_dir, )[:700])
    if attempts:
        req["failed_earlier_attempts"] = attempts
    if not rep_path.is_file():
        req["outcome"] = "NOT SUBMITTED / no report"
        return {"requests": req, "points": pts}
    try:
        rep = json.loads(rep_path.read_text())
    except json.JSONDecodeError:
        req["outcome"] = "NO JSON (klt failed before a report existed): " + scrub((d / "klt.stderr").read_text()[-800:], run_dir)
        for pt in pts.values():
            pt["reason"] = "fleet refused/failed before any corner ran (see request outcome)"
        return {"requests": req, "points": pts}
    if "corners" not in rep:
        req["outcome"] = "klt error (no corners reported): " + scrub(str((rep.get("error") or {}).get("message", rep))[:600], run_dir)
        for pt in pts.values():
            pt["reason"] = "fleet refused/failed before any corner ran (see request outcome)"
        return {"requests": req, "points": pts}
    remote = (rep.get("environment") or {}).get("remote") or {}
    req.update({k: remote.get(k) for k in ("job_id", "instance_type", "lifecycle", "runner_klt_version", "client_klt_version", "elapsed_seconds", "state")})
    req["outcome"] = rep.get("status")
    req["corner_count"] = rep.get("corner_count")
    for c in rep.get("corners", []):
        cid = corner_id(c["process"], c["temperature_c"], c["supply_v"]["vset"])
        pt = pts.get(cid)
        if pt is None:
            continue
        art = c.get("artifacts") or {}
        log_text = Path(art["log"]).read_text() if art.get("log") and Path(art["log"]).is_file() else ""
        ngv = re.findall(r"(ngspice-\d+) done", log_text)
        pt.update({"klt_status": c.get("status"), "runtime_s": c.get("runtime_s"), "ngspice": ngv[0] if ngv else None,
                   "meas": {m["name"]: m.get("value") for m in c.get("measurements", [])},
                   "diagnostics": [f"{dg.get('severity')}/{dg.get('code')}: {scrub(dg.get('message', ''), run_dir)[:300]}" for dg in c.get("diagnostics", [])]})
        wp = Path(art["waveform"]) if art.get("waveform") else None
        if wp is None or not wp.is_file():
            pt.update({"status": "nonconverged", "reason": "no waveform retrieved: " + classify_failure(c, log_text)})
            continue
        wave = qc.load_wave(wp)
        g = qc.grade(wave, state, c["supply_v"]["vset"], man)
        pt.pop("reason", None)
        pt.update(g)
        if g["status"] != "nonconverged":
            iq_meas = pt["meas"].get("iq_trail_neg")
            pt["meas_agree_rel"] = (abs((-iq_meas) - g["i_total_a"]) / abs(g["i_total_a"])) if iq_meas is not None and g.get("i_total_a") else None
        keep = ["v(vdd)", "v(resetn)", "i(bvdd)", *qc.SUBCELLS.values(), "i(vrst)", "v(ptat)", "v(ctat)"]
        traces.setdefault(state, {})[cid] = decimate(wave, keep)
    return {"requests": req, "points": pts}


def stats(vals: list[float]):
    if not vals:
        return None
    return {"n": len(vals), "min": min(vals), "median": statistics.median(vals), "max": max(vals)}


def derive_temp_iq(por: dict, tot: dict) -> dict:
    out = {}
    for cid in tot:
        a, b = por[cid], tot[cid]
        if a["status"] == "ok" and b["status"] == "ok":
            st, why = "ok", ""
        else:
            st = "excluded"
            why = f"por-iq {a['status']}, iq-total {b['status']}"
        if "i_total_a" in a and "i_total_a" in b:
            out[cid] = {"id": cid, "status": st, "reason": why, "temp_iq_a": b["i_total_a"] - a["i_total_a"],
                        "temp_core_attrib_delta_a": b["subcell_a"]["temp_core"] - a["subcell_a"]["temp_core"]}
        else:
            out[cid] = {"id": cid, "status": "excluded", "reason": why or "no value", "temp_iq_a": None}
    return out


def summarize(per: dict, temp: dict) -> dict:
    s = {}
    for state in STATES:
        pts = per[state]["points"]
        counts: dict[str, int] = {}
        for p in pts.values():
            counts[p["status"]] = counts.get(p["status"], 0) + 1
        ok = [p for p in pts.values() if p["status"] == "ok"]
        withval = [p for p in pts.values() if p.get("i_total_a") is not None]
        entry = {"counts": counts, "ok_only": stats([p["i_total_a"] for p in ok]), "all_with_value": stats([p["i_total_a"] for p in withval])}
        if ok:
            hi, lo = max(ok, key=lambda p: p["i_total_a"]), min(ok, key=lambda p: p["i_total_a"])
            entry["worst_corner_max"] = {"id": hi["id"], "i_total_a": hi["i_total_a"]}
            entry["best_corner_min"] = {"id": lo["id"], "i_total_a": lo["i_total_a"]}
        typ = pts.get("tt_27c_3.30v")
        entry["typ_tt_27c_3p30v"] = {"status": typ["status"], "i_total_a": typ.get("i_total_a")} if typ else None
        entry["excluded"] = [{"id": p["id"], "status": p["status"], "why": "; ".join(p.get("nonphysical_reasons", []) + p.get("unsettled_reasons", []) + ([p["reason"]] if p.get("reason") else []))} for p in pts.values() if p["status"] != "ok"]
        attr = {}
        for k in qc.SUBCELLS:
            vals = [p["subcell_a"][k] for p in ok]
            tv = typ["subcell_a"][k] if typ and typ.get("subcell_a") and typ["status"] == "ok" else None
            attr[k] = {"ok_only": stats(vals), "typ_tt_27c_3p30v": tv}
        entry["attribution"] = attr
        entry["sum_vs_direct_max_abs_rel"] = max((abs(p["sum_minus_direct_rel"]) for p in ok), default=None)
        if state == "por-iq":
            entry["contention_a"] = stats([p["contention_a"] for p in ok])
            entry["less_contention_a"] = stats([p["i_total_less_contention_a"] for p in ok])
            entry["contention_worst"] = max(((p["contention_a"], p["id"]) for p in ok), default=None)
        s[state] = entry
    tok = [t for t in temp.values() if t["status"] == "ok"]
    tall = [t for t in temp.values() if t.get("temp_iq_a") is not None]
    ent = {"counts": {"ok": len(tok), "excluded": len(temp) - len(tok)}, "ok_only": stats([t["temp_iq_a"] for t in tok]), "all_with_value": stats([t["temp_iq_a"] for t in tall])}
    if tok:
        ent["worst_corner_max"] = max(((t["temp_iq_a"], t["id"]) for t in tok))
        ent["best_corner_min"] = min(((t["temp_iq_a"], t["id"]) for t in tok))
    ent["typ_tt_27c_3p30v"] = temp.get("tt_27c_3.30v")
    s["temp-iq"] = ent
    return s


def ua(x):
    return "-" if x is None else f"{x * 1e6:.3f}"


def render_md(rec: dict) -> str:
    L = [f"# Record {rec['record_id']}", ""]
    L += sim_common.render_record_id_experiment(rec["record_id"], SLUG, rec["experiment"]["title"])
    L += [f"- **Claim**: {rec['experiment']['claim']}",
          "- **Variant**: as-drawn -- the committed `design/netlist/temp_por_top.spice` (XMN1 at L=20 W=0.42 since #101/#111); no netlist edit other than the 0 V attribution ammeters (see Attribution).",
          f"- **Netlist provenance**: schematic (`{rec['experiment']['provenance_source']}`)"]
    L += sim_common.render_pdk_tools_repo_state(rec)
    L += [f"- **Fleet**: {rec['fleet_note']}",
          f"- **Corner matrix run**: process {', '.join(rec['matrix']['process'])}; temperature {rec['matrix']['temperature_c']} C; supply {rec['matrix']['supply_v']} V -- 45 points per state, 90 total; {rec['matrix']['n_with_value']} points have a settled-window value, {rec['matrix']['n_ok']} are `ok` (full declared grid; no subset).",
          "- **Statistical convention**: N/A (corner-matrix measurement)", ""]
    L += ["## Measurement definitions (exploratory; none is a ratified bound; no ceiling is proposed)"]
    m = rec["definitions"]
    for k, v in m.items():
        L.append(f"- **{k}**: {v}")
    L += ["", "## Per-request fleet submissions", "| state | outcome | job id | instance | lifecycle | runner klt | state | corners |", "|---|---|---|---|---|---|---|---|"]
    for st in STATES:
        r = rec["requests"][st]
        L.append(f"| {st} | {r.get('outcome')} | {r.get('job_id')} | {r.get('instance_type')} | {r.get('lifecycle')} | {r.get('runner_klt_version')} | {r.get('state')} | {r.get('corner_count')} |")
        for a in r.get("failed_earlier_attempts", []):
            L.append(f"|  | earlier attempt: {a} | | | | | | |")
    L.append("")
    S = rec["summary"]
    any_val = any(S[s]["all_with_value"] for s in STATES)
    L += ["## Result summary (uA; I = settled VDD supply current)"]
    if not any_val:
        L += ["**No point produced a value: the grid did not run (see the fleet outcome above).** No result is claimed; the issue stays open."]
    L += ["", "| quantity | n ok / 45 | min | median | max | worst (max) corner | typ tt/27C/3.30V | n incl. flagged | min..max incl. flagged |", "|---|---|---|---|---|---|---|---|---|"]
    for st, label in (("por-iq", "por-iq (RESETn forced low)"), ("temp-iq", "temp-iq (incremental = iq-total - por-iq)"), ("iq-total", "iq-total (direct)")):
        e = S[st]
        ok, al = e["ok_only"], e["all_with_value"]
        typ = e["typ_tt_27c_3p30v"]
        if st == "temp-iq":
            tv = ua(typ["temp_iq_a"]) if typ else "-"
            worst = f"{e['worst_corner_max'][1]} ({ua(e['worst_corner_max'][0])})" if e.get("worst_corner_max") else "-"
            nok = e["counts"]["ok"]
        else:
            tv = ua(typ["i_total_a"]) + (f" ({typ['status']})" if typ and typ["status"] != "ok" else "") if typ else "-"
            worst = f"{e['worst_corner_max']['id']} ({ua(e['worst_corner_max']['i_total_a'])})" if e.get("worst_corner_max") else "-"
            nok = e["counts"].get("ok", 0)
        L.append(f"| {label} | {nok} | {ua(ok and ok['min'])} | {ua(ok and ok['median'])} | {ua(ok and ok['max'])} | {worst} | {tv} | {al['n'] if al else 0} | {ua(al and al['min'])} .. {ua(al and al['max'])} |")
    L.append("")
    L.append("Status counts: " + "; ".join(f"{st}: {S[st]['counts']}" for st in STATES + ["temp-iq"]))
    L += ["", "### Excluded / flagged points (not `ok`), by state"]
    for st in STATES:
        ex = S[st]["excluded"]
        if not ex:
            L.append(f"- {st}: none.")
        for x in ex:
            L.append(f"- {st} `{x['id']}`: **{x['status']}** -- {x['why']}")
    L += ["", "Statistics above are given twice: `ok`-only (columns min/median/max) and over every point that produced a settled-window value, flagged ones included (last column). A non-physical-branch point is excluded from the `ok` statistics ONLY because it shows the documented signature (design/temp_core.md ~l.145-172; issue #86 still open), never because it is large or small.", ""]
    L += ["## Per-sub-cell attribution (ATTRIBUTION ONLY; never summed into iq-total) -- uA, `ok` points", "| state | sub-cell | min | median | max | typ tt/27C/3.30V |", "|---|---|---|---|---|---|"]
    for st in STATES:
        for k, v in S[st]["attribution"].items():
            o = v["ok_only"]
            L.append(f"| {st} | {k} | {ua(o and o['min'])} | {ua(o and o['median'])} | {ua(o and o['max'])} | {ua(v['typ_tt_27c_3p30v'])} |")
    L += ["", "## Direct-vs-attribution-sum discrepancy (iq-total is the direct -i(BVDD); the sum is the four sub-cell ammeters)"]
    for st in STATES:
        d = S[st]["sum_vs_direct_max_abs_rel"]
        L.append(f"- {st}: max |sum - direct| / direct over `ok` points = {('%.3e' % d) if d is not None else 'n/a'}. The deck has no other VDD consumer at the top level, so a small value confirms the instrumentation (KCL), it is not an independent physical result.")
    L += ["- NOTE on temp-iq sign: por-iq includes the forced-reset contention current (see below), which is absent in the released iq-total state, so the incremental temp-iq = iq-total - por-iq is NEGATIVE at every `ok` point. It is reported as measured and is NOT the sensor's own current; the temp_core attribution delta and the por-iq-less-contention figure are the meaningful comparisons.", ""]
    L += ["- temp-iq = iq-total - por-iq is the incremental difference of the two direct measurements, so `por-iq + temp-iq = iq-total` holds by construction for that row; the temp_core attribution delta (temp_core current in iq-total minus in por-iq) is in the JSON twin for comparison.", ""]
    L += ["## How RESETn was held low for por-iq, and the contention current"]
    L.append(rec["definitions"]["por-iq hold"])
    c = S["por-iq"].get("contention_a")
    if c:
        L.append(f"- Contention current i(VRST) (DUT pushing RESETn high against the force; INCLUDED in the por-iq above): min {ua(c['min'])} / median {ua(c['median'])} / max {ua(c['max'])} uA over `ok` points; worst corner {S['por-iq']['contention_worst'][1]}.")
        lc = S["por-iq"]["less_contention_a"]
        L.append(f"- por-iq less contention (VDD current minus i(VRST)): min {ua(lc['min'])} / median {ua(lc['median'])} / max {ua(lc['max'])} uA. Both numbers are reported; neither is a proposed ceiling.")
    else:
        L.append("- No contention data (no `ok` por-iq point).")
    L.append("")
    if rec.get("crosscheck"):
        L += ["## Local cross-check (single corner tt / 27 C / 3.30 V, `--backend local`)", rec["crosscheck"]["text"], ""]
    L += ["## Per-point status (all 45 points per state)"]
    for st in STATES:
        L += ["", f"### {st}", "| point | status | I (uA) | drift | pk-pk | bias_core | por_comparator | por_output_chain | temp_core | sum-direct | contention (uA) | note |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for pt in rec["points"][st].values():
            sc = pt.get("subcell_a") or {}
            note = "; ".join(pt.get("nonphysical_reasons", []) + pt.get("unsettled_reasons", []) + ([pt["reason"]] if pt.get("reason") else []))
            f = lambda x: "-" if x is None else f"{x:.2e}"  # noqa: E731
            L.append(f"| {pt['id']} | {pt['status']} | {ua(pt.get('i_total_a'))} | {f(pt.get('drift_rel'))} | {f(pt.get('pk_pk_rel'))} | {ua(sc.get('bias_core'))} | {ua(sc.get('por_comparator'))} | {ua(sc.get('por_output_chain'))} | {ua(sc.get('temp_core'))} | {f(pt.get('sum_minus_direct_rel'))} | {ua(pt.get('contention_a'))} | {note} |")
    L += ["", "### temp-iq (derived, incremental)", "| point | status | temp-iq (uA) | temp_core attribution delta (uA) | note |", "|---|---|---|---|---|"]
    for t in rec["temp_iq"].values():
        L.append(f"| {t['id']} | {t['status']} | {ua(t.get('temp_iq_a'))} | {ua(t.get('temp_core_attrib_delta_a'))} | {t.get('reason', '')} |")
    L += ["", "## Absent coverage (stated, not hidden)"]
    L += [f"- {a}" for a in ABSENT]
    L += ["", "## Links"]
    L += [f"- {k}: `{v}`" for k, v in rec["links"].items()]
    L += [f"- **Timestamp / author**: {rec['timestamp']}, {rec['author']}", f"- **Supersedes**: {rec['supersedes'] or '(none)'}", "",
          "Written by `sim/iq-top/run_iq_campaign.py`. Append-only: never edit this file -- a correction is a new record with a `Supersedes` field (see `sim/README.md`).", ""]
    return "\n".join(L)


ABSENT = [
    "Constant-VDD settled current only: supply-ramp behavior (inrush, release timing) is sim/supply-ramp-top, not measured here.",
    "No ll/hh passive-skew axis and no mismatch Monte Carlo: this is the {tt,ss,ff,sf,fs} x temperature x supply corner grid only.",
    "PTAT/CTAT are left open (no output buffer exists), so no sensor-output load current is included in temp-iq.",
    "MASSIST's current is inside the por_output_chain attribution; it is not separated from the rest of that sub-cell here.",
    "No numeric ceiling is proposed; a follow-on decision record would use these records as evidence (DR-003 TBD-4/5/6).",
    "The fleet PDK commit is not reported by the runner; agreement with the local cross-check is the only evidence the fleet model library matches the pin.",
]

DEFS = {
    "state definitions": "por-iq = RESETn asserted (low), directly simulated; iq-total = natural released state, directly simulated in its own run (never a sum); temp-iq = iq-total - por-iq, labelled incremental.",
    "por-iq hold": "- RESETn is a DUT output (releases by itself above VPOR-rise), so the por-iq testbench (`testbench/tb_temp_por_iq_por.sch`) forces it low with a 0 V voltage source VRST from RESETn to VSS for the whole run. The DUT netlist is untouched. VRST's current is not part of the VDD measurement; the output stage's contention against it IS inside -i(BVDD) and is read as i(VRST).",
    "measurement": "transient from a physical 0 V start, VDD = min(final, 1e4 V/s * t), held to 30 ms; I = -i(BVDD) time-averaged over the trailing 25-30 ms window.",
    "settling": "ok only if trailing-window mean is within 1% of the 20-25 ms window mean, trailing pk-pk <= 2% of the mean, VDD within 5 mV of target, and the asked-for state holds (iq-total: RESETn > 0.8*VDD; por-iq: RESETn <= 50 mV). Otherwise `unsettled`.",
    "non-physical-branch": "any saved node outside [-0.3 V, VDD+0.5 V] in the trailing window, settled total current <= 0, or a settled sub-cell current < -1 nA (the issue #19/#22/#86 signature documented in design/temp_core.md ~l.145-172). Applied identically in both states.",
    "nonconverged": "klt/ngspice produced no waveform for the point, or the run ended before the trailing window.",
    "attribution": "four 0 V ammeters in series with each sub-cell's VDD pin, inserted by the driver in the generated deck (electrically ideal; same deck both states).",
}


def cmd_record(args) -> int:
    man = load_manifest()
    run_dir = BUILD / args.run_id
    meta = json.loads((run_dir / "run.json").read_text())
    pin = cr.load_pin()
    pdk = cr.resolve_pdk(pin)
    git_info = cr.git_state()
    now = datetime.now(timezone.utc)
    record_id = f"{now:%Y%m%d}-{now:%H%M%S}-{git_info['sha']}"
    rate = man["measurement"]["rate_v_per_s"]
    rec_dir, corners_dir, snap_dir = HERE / "records", HERE / "corners" / record_id, HERE / "netlist-snapshots" / record_id
    for pth in (rec_dir / f"{record_id}.md", rec_dir / f"{record_id}.json", corners_dir, snap_dir):
        if pth.exists():
            raise SystemExit(f"{pth} exists -- sim/ is append-only")
    traces: dict = {}
    per = {st: analyze_state(st, run_dir, man, traces) for st in STATES}
    temp = derive_temp_iq(per["por-iq"]["points"], per["iq-total"]["points"])
    summary = summarize(per, temp)
    corners_dir.mkdir(parents=True)
    snap_dir.mkdir(parents=True)
    for st in STATES:
        d = run_dir / st / sim_common.rate_tag(rate)
        for name in ("netlist.spice", "request.json"):
            if (d / name).is_file():
                (snap_dir / f"{st}.{name}").write_text(scrub((d / name).read_text(), run_dir))
        if (d / "report.json").is_file():
            (corners_dir / f"{st}.klt-report.json").write_text(scrub((d / "report.json").read_text(), run_dir))
        if (d / "klt.stderr").is_file() and (d / "klt.stderr").read_text().strip():
            (corners_dir / f"{st}.klt.stderr").write_text(scrub((d / "klt.stderr").read_text(), run_dir))
        if st in traces:
            with gzip.open(corners_dir / f"{st}.traces.json.gz", "wt") as fh:
                json.dump(traces[st], fh)
    # local cross-check
    xc = None
    parts = []
    for st in STATES:
        xp = run_dir / "crosscheck" / STATE_TAG[st] / "report.json"
        if not xp.is_file():
            continue
        try:
            xrep = json.loads(xp.read_text())
        except json.JSONDecodeError:
            parts.append(f"{st}: local probe produced no JSON.")
            continue
        xcor = (xrep.get("corners") or [None])[0]
        if not xcor or not (xcor.get("artifacts") or {}).get("waveform"):
            parts.append(f"{st}: local probe returned no waveform ({xcor and xcor.get('status')}); UNRESOLVED -- the single local ngspice-42 run was stopped by the operator after ~33 min / ~64 CPU-min without finishing (shared host), so this state has NO local cross-check and the fleet value for tt/27C/3.30V is not cross-checked.")
            continue
        g = qc.grade(qc.load_wave(Path(xcor["artifacts"]["waveform"])), st, 3.3, man)
        fl = per[st]["points"].get("tt_27c_3.30v", {})
        txt = f"{st}: local ngspice-42 status **{g['status']}**, I = {ua(g.get('i_total_a'))} uA"
        if "contention_a" in g:
            txt += f", contention {ua(g['contention_a'])} uA"
        if fl.get("i_total_a") is not None and g.get("i_total_a"):
            rel = abs(fl["i_total_a"] - g["i_total_a"]) / abs(g["i_total_a"])
            txt += f"; fleet {fl.get('ngspice') or ''} status {fl['status']}, I = {ua(fl['i_total_a'])} uA; |fleet - local|/local = {rel:.3%} (tolerance for 'matches': 2%, stated here because the engines differ: ngspice-42 local vs the fleet runner's)"
        else:
            txt += "; no fleet value for this point to compare with (fleet did not return it), so this probe is the only value for the typical corner and is NOT a cross-check of anything"
        parts.append(txt + ".")
    if parts:
        xc = {"text": " ".join(parts)}
    all_pts = [p for st in STATES for p in per[st]["points"].values()]
    ngs = sorted({p["ngspice"] for p in all_pts if p.get("ngspice")})
    runners = sorted({per[s]["requests"].get("runner_klt_version") for s in STATES if per[s]["requests"].get("runner_klt_version")})
    jobs = [per[s]["requests"].get("job_id") for s in STATES]
    fleet_note = (f"batch jobs {jobs}; runner klt {', '.join(runners) or 'unknown'}; fleet ngspice {', '.join(ngs) or 'unknown'}; client {meta['klt_client']}; "
                  "client/runner version skew accepted with batch.runner_version_check=warn")
    record = {
        "record_id": record_id, "timestamp": now.strftime("%Y-%m-%dT%H:%M:%SZ"), "author": args.author or cr.default_author(), "supersedes": args.supersedes,
        "experiment": {k: man[k] for k in ("slug", "title", "claim", "provenance", "provenance_source", "statistical_convention")},
        "pdk": {"variant": pdk.variant, "installed_commit": pdk.installed_commit, "pinned_commit": pin["open_pdks_commit"], "matches_pin": pdk.matches_pin, "lib_file": MODEL_LIB + " (resolved on the runner as /opt/pdk/sky130A/...)"},
        "tools": {"ngspice": f"{cr.first_line(['ngspice', '-v'])} (host; the grid ran on the fleet)", "xschem": cr.first_line(["xschem", "--version"]), "platform": cr.tool_versions()["platform"], "python": cr.tool_versions()["python"], "klt_client": meta["klt_client"]},
        "git": git_info, "fleet_note": fleet_note,
        "matrix": {**man["corners"], "n_points_per_state": 45, "n_with_value": sum(1 for p in all_pts if p.get("i_total_a") is not None), "n_ok": sum(1 for p in all_pts if p["status"] == "ok")},
        "definitions": DEFS, "requests": {s: per[s]["requests"] for s in STATES},
        "points": {s: per[s]["points"] for s in STATES}, "temp_iq": temp, "summary": summary, "crosscheck": xc, "absent_coverage": ABSENT,
        "links": {"testbench_por": "sim/iq-top/testbench/tb_temp_por_iq_por.sch", "testbench_total": "sim/iq-top/testbench/tb_temp_por_iq_total.sch", "manifest": "sim/iq-top/experiment.json",
                  "driver": "sim/iq-top/run_iq_campaign.py", "checker": "sim/iq-top/iq_checker.py", "netlist_snapshots": f"sim/iq-top/netlist-snapshots/{record_id}/",
                  "corners_dir": f"sim/iq-top/corners/{record_id}/", "json": f"sim/iq-top/records/{record_id}.json", "record": f"sim/iq-top/records/{record_id}.md"},
    }
    rec_dir.mkdir(parents=True, exist_ok=True)
    (rec_dir / f"{record_id}.json").write_text(json.dumps(record, indent=1, sort_keys=True, default=float) + "\n")
    (rec_dir / f"{record_id}.md").write_text(render_md(record))
    print(f"record {record_id}: {record['matrix']['n_ok']} ok / 90, {record['matrix']['n_with_value']} with value; dirty={git_info['dirty']}")
    return 0


# --------------------------------------------------------------------------
# selftest
# --------------------------------------------------------------------------


def cmd_selftest(args) -> int:
    man = load_manifest()
    git_info = cr.git_state()
    now = datetime.now(timezone.utc)
    record_id = f"{now:%Y%m%d}-{now:%H%M%S}-{git_info['sha']}-checker-selftest"
    (HERE / "selftest").mkdir(exist_ok=True)
    rows = qc.run_selftest(man, HERE / "selftest")
    ok = all(r["ok"] for r in rows)
    # re-grade the committed fixtures from disk: the on-disk waveform is the evidence
    again = {}
    for name, state in (("settled_constant_total", "iq-total"), ("drifting_total", "iq-total")):
        w = qc.load_wave(HERE / "selftest" / f"{name}.wave.json")
        again[name] = qc.grade(w, state, 3.3, man)["status"]
    ok = ok and again["settled_constant_total"] == "ok" and again["drifting_total"] == "unsettled"
    rec_dir = HERE / "records"
    rec_dir.mkdir(exist_ok=True)
    if (rec_dir / f"{record_id}.md").exists():
        raise SystemExit("record exists")
    doc = {"record_id": record_id, "timestamp": now.strftime("%Y-%m-%dT%H:%M:%SZ"), "author": args.author or cr.default_author(), "supersedes": args.supersedes,
           "kind": "settling/physicality checker self-test (synthetic currents, no simulation)", "git": git_info, "cases": rows, "fixtures_regraded_from_disk": again, "overall_pass": ok}
    (rec_dir / f"{record_id}.json").write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n")
    L = [f"# Record {record_id}", "", f"- **Record ID**: {record_id}", "- **Experiment**: `iq-top` -- settling/physicality checker self-test",
         "- **Claim**: proves `iq_checker.py` does not pass a drifting or non-released current as settled, and does pass a clean constant one (so it is not vacuous), on synthetic currents with known answers. No simulation involved; the campaign records use the same code and thresholds (`experiment.json` `measurement`).",
         f"- **Repo state**: `{git_info['sha']}` on `{git_info['branch']}`" + (" (working tree dirty at run time)" if git_info["dirty"] else " (clean working tree)"),
         "- **Netlist provenance**: synthetic waveforms generated by `iq_checker.synth()`; two are committed under `sim/iq-top/selftest/`.", "",
         "| case | state | expected | got | drift | pk-pk | ok | reasons |", "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        f = lambda x: "-" if x is None else f"{x:.3e}"  # noqa: E731
        L.append(f"| {r['case']} | {r['state']} | {r['expected']} | {r['got']} | {f(r['drift_rel'])} | {f(r['pk_pk_rel'])} | {'yes' if r['ok'] else 'NO'} | {'; '.join(r['reasons']) or '-'} |")
    L += ["", f"Committed fixtures re-read from disk and re-graded: {again}.", "", f"**Overall: {'PASS' if ok else 'FAIL'}**", "",
          f"- **Timestamp / author**: {doc['timestamp']}, {doc['author']}", f"- **Supersedes**: {args.supersedes or '(none)'}", "", "Written by `sim/iq-top/run_iq_campaign.py selftest`. Append-only.", ""]
    (rec_dir / f"{record_id}.md").write_text("\n".join(L))
    print(f"selftest record {record_id}: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 2


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--state", action="append", choices=STATES)
    r.add_argument("--jobs", type=int, default=2)
    r.add_argument("--run-id")
    r.add_argument("--retry-failed", action="store_true")
    r.add_argument("--capacity-wait", type=float, default=0)
    x = sub.add_parser("crosscheck")
    x.add_argument("--run-id", required=True)
    x.add_argument("--state", action="append", choices=STATES)
    c = sub.add_parser("record")
    c.add_argument("--run-id", required=True)
    c.add_argument("--author")
    c.add_argument("--supersedes")
    s = sub.add_parser("selftest")
    s.add_argument("--author")
    s.add_argument("--supersedes")
    args = ap.parse_args(argv)
    return {"run": cmd_run, "crosscheck": cmd_crosscheck, "record": cmd_record, "selftest": cmd_selftest}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
