#!/usr/bin/env python3
"""Solver / ramp-rate discrimination sweep for the temp_core cold-start FAILs (issue #86).

Question: are the six Overall-FAIL points in sim/temp-core-startup/ and
sim/temp-core-startup-en-delayed/ (record ee63b45, dirty tree) solver artifacts (a
non-physical branch landing that moves with integration settings) or real failures?

Every (EN scenario x solver/ramp variant) is ONE ``klt sim`` corner request over the FULL
45-point PVT matrix, submitted to the Spot batch fleet with an explicit ``--backend batch``
(sim/README.md rule 6: a solver sweep over only the six points proves little).  This script
never launches ngspice over a grid itself and never falls back to a local grid if the fleet
refuses; refusals are recorded.  ``probe`` runs SINGLE local points only.

Stages:  run | probe | record
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR / "bin"))
import sim_common  # noqa: E402

cr = sim_common.load_corner_run()
SLUG = "temp-core-startup-solver"
BUILD = REPO_ROOT / "sim" / "build" / SLUG
MODEL_LIB = "libs.tech/combined/sky130.lib.spice"
say = sim_common.say

PROCS = ["tt", "ss", "ff", "sf", "fs"]
TEMPS = [-40, 27, 125]
SUPPLIES = [2.97, 3.3, 3.63]
TSTOP = 10e-3
STEP = 10e-6

# The six FAIL points the issue names (EN scenario, corner id)
SIX = {
    "en-high": ["tt_-40c_3.30v", "tt_125c_3.30v", "ff_-40c_3.30v"],
    "en-delayed": ["tt_27c_3.63v", "tt_125c_3.63v", "sf_-40c_2.97v"],
}

# variant -> (.options extra, tramp seconds).  base = the deck of the ee63b45 records.
VARIANTS = {
    "base": ("method=gear trtol=50", 100e-6),
    "trtol7": ("method=gear trtol=7", 100e-6),
    "reltol2e-4": ("method=gear trtol=50 reltol=2e-4", 100e-6),
    "ramp1u": ("method=gear trtol=50", 1e-6),
    "ramp2m": ("method=gear trtol=50", 2e-3),
}
SCENARIOS = ["en-high", "en-delayed"]

# Measurement windows: copied from the existing experiment.json files (NOT relaxed).
WINDOWS = {
    "ptat": (0.3, 2.6), "ctat": (0.2, 1.1), "na": (-1.0, 4.7), "nb": (-1.0, 4.7),
    "isup": (1e-8, 5e-5), "bias_ok": (2.0, 3.7), "ptat_settled": (0.0, 1e-3), "ctat_settled": (0.0, 1e-3),
}


def corner_id(p, t, v):
    return f"{p}_{cr.fmt_temp(t)}c_{v:.2f}v"


def grid():
    return [(p, t, v) for p in PROCS for t in TEMPS for v in SUPPLIES]


def subckt_text(name):
    txt = (REPO_ROOT / "design" / "netlist" / f"{name}.spice").read_text()
    return "\n".join(ln for ln in txt.splitlines() if ln.strip().lower() != ".end") + "\n"


def build_netlist(scenario, variant):
    opts, tramp = VARIANTS[variant]
    ten_start = tramp + 200e-6
    ten_end = ten_start + 50e-6
    en_node = "VDD" if scenario == "en-high" else "EN"
    lines = [
        f"* {SLUG} ({scenario}, {variant}): generated by sim/{SLUG}/run_solver_sweep.py -- do not edit",
        "* Same circuit/topology as sim/temp-core-startup{,-en-delayed}/testbench (V1 PWL ramp 0->vsup over tramp;",
        "* XBIAS + XDUT; EN tied to VDD or released after the supply is up). VDD is a behavioural source equal",
        "* to that PWL ramp, driven from klt's swept VSET source. DUT = committed design/netlist/{bias,temp}_core.spice.",
        f".param tramp={tramp:.9g}",
        f".param ten_start={ten_start:.9g}",
        f".param ten_end={ten_end:.9g}",
        f".param tstop={TSTOP:.9g}",
        f".options wnflag=1 {opts}",
        "* ng_nomodcheck: same as sim/spiceinit; carried in the netlist because the fleet runner ignores options.ngspice_init",
        ".control", "set ng_nomodcheck", ".endc",
        "VSET vsetn 0 3.3",
        "* unit PWL ramp keeps the exact breakpoint at tramp that the original V1 PWL source had; BVDD scales it by the swept VSET",
        "VRAMP rampn 0 PWL(0 0 {tramp} 1 {tstop} 1)",
        "BVDD VDD 0 V = v(vsetn)*v(rampn)",
    ]
    if scenario == "en-delayed":
        lines += ["VENR enrampn 0 PWL(0 0 {ten_start} 0 {ten_end} 1 {tstop} 1)", "BEN EN 0 V = v(vsetn)*v(enrampn)"]
    lines += [
        "XBIAS VDD 0 IBIAS VREF BIAS_OK bias_core",
        f"XDUT VDD 0 IBIAS {en_node} PTAT CTAT temp_core",
        "",
        subckt_text("bias_core"),
        subckt_text("temp_core"),
        ".end",
    ]
    return "\n".join(lines) + "\n"


def build_request(backend, corners=None, timeout=3000):
    p, t, v = (corners or (PROCS, TEMPS, SUPPLIES))
    req = {
        "netlist": "netlist.spice",
        "backend": backend,
        "models": {"pdk": "sky130A", "lib": MODEL_LIB},
        "corners": {"process": p, "supply_v": {"vset": v}, "temperature_c": t},
        "analysis": {"kind": "tran", "args": f"{STEP:.6g} {TSTOP:.6g} uic"},
        "measurements": [{"name": "vdd_end", "spice": f".meas tran vdd_end FIND v(vdd) AT={TSTOP:.6g}", "unit": "V"}],
        "options": {"timeout_s": timeout, "keep_artifacts": True, "waveforms": True},
    }
    if backend == "batch":
        req["batch"] = {"runner_version_check": "warn"}
    return req


def klt_version():
    p = subprocess.run(["klt", "--version"], capture_output=True, text=True)
    return (p.stdout.strip() or p.stderr.strip())


def cmd_run(args):
    now = datetime.now(timezone.utc)
    git = cr.git_state()
    run_id = args.run_id or f"{now:%Y%m%d-%H%M%S}-{git['sha']}"
    run_dir = BUILD / run_id
    run_dir.mkdir(parents=True, exist_ok=args.resume)
    combos = [(s, v) for s in (args.scenario or SCENARIOS) for v in (args.variant or list(VARIANTS))]
    this = {"started_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"), "klt_client": klt_version(),
            "klt_sim_backend_env": os.environ.get("KLT_SIM_BACKEND"), "git": git, "combos": combos}
    if args.resume and (run_dir / "run.json").is_file():
        # keep the original run's provenance; a resume is appended, never overwrites it
        meta = json.loads((run_dir / "run.json").read_text())
        meta.setdefault("resumes", []).append(this)
        cur = this
    else:
        meta = {"run_id": run_id, **this}
        cur = meta
    (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")

    def one(sv):
        s, v = sv
        name = f"{s}__{v}"
        d = run_dir / name
        if sim_common.report_usable(d / "report.json"):
            return {"combo": name, "skipped": "usable report exists"}
        d.mkdir(parents=True, exist_ok=True)
        (d / "netlist.spice").write_text(build_netlist(s, v))
        (d / "request.json").write_text(json.dumps(build_request("batch"), indent=2) + "\n")
        say(f"[submit] {name}: 45 points -> batch fleet")
        p = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "batch", "-o", str(d / "out"), "--format", "json"],
                           capture_output=True, text=True, timeout=4 * 3600)
        (d / "report.json").write_text(p.stdout)
        (d / "klt.stderr").write_text(p.stderr)
        try:
            st = json.loads(p.stdout).get("status", "?")
        except json.JSONDecodeError:
            st = "NO-JSON"
        say(f"[done]   {name}: exit {p.returncode}, status {st}")
        return {"combo": name, "exit": p.returncode, "status": st}

    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, args.jobs)) as ex:
        for f in [ex.submit(one, c) for c in combos]:
            try:
                results.append(f.result())
            except Exception as err:  # noqa: BLE001 -- recorded
                results.append({"error": repr(err)})
                say(f"[error] {err!r}")
    cur["submit_results"] = results
    (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")
    print(f"raw outputs: {run_dir}")
    return 0


def parse_cid(cid):
    p, t, v = cid.split("_")
    return p, int(t[:-1]), float(v[:-1])


def cmd_probe(args):
    """Single-corner LOCAL probes (never a grid)."""
    run_dir = BUILD / args.run_id
    for item in args.point:
        scen, variant, cid = item.split(":")
        p, t, v = parse_cid(cid)
        d = run_dir / "probe" / f"{scen}__{variant}__{cid}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "netlist.spice").write_text(build_netlist(scen, variant))
        req = build_request("local", ([p], [t], [v]))
        (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
        say(f"[probe] local single corner {scen} {variant} {cid}")
        pr = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "local", "-o", str(d / "out"), "--format", "json"],
                            capture_output=True, text=True, timeout=3600)
        (d / "report.json").write_text(pr.stdout)
        (d / "klt.stderr").write_text(pr.stderr)
        say(f"[probe] exit {pr.returncode}")
    return 0


def interp(t, y, tq):
    import bisect
    i = bisect.bisect_left(t, tq)
    if i <= 0:
        return y[0]
    if i >= len(t):
        return y[-1]
    f = (tq - t[i - 1]) / (t[i] - t[i - 1])
    return y[i - 1] + f * (y[i] - y[i - 1])


def grade_wave(wave, scenario, variant):
    """Same quantities and windows as the experiment.json measurements, read from the saved waveform."""
    import math
    t = wave.get("time", [])
    need = ["v(ptat)", "v(ctat)", "v(xdut.na)", "v(xdut.nb)", "i(bvdd)", "v(bias_ok)"]
    miss = [n for n in need if n not in wave]
    if len(t) < 20 or miss:
        return {"status": "nonconverged", "reason": f"waveform short/missing (n={len(t)}, missing={miss})"}
    if any((not math.isfinite(x)) for n in need for x in wave[n]):
        return {"status": "nonconverged", "reason": "non-finite samples"}
    if t[-1] < TSTOP * 0.999:
        return {"status": "nonconverged", "reason": f"ended at {t[-1]:.4g}s < tstop"}
    te, tb = t[-1], t[-1] - 1e-3
    m = {
        "ptat": wave["v(ptat)"][-1], "ctat": wave["v(ctat)"][-1],
        "na": wave["v(xdut.na)"][-1], "nb": wave["v(xdut.nb)"][-1],
        "isup": -wave["i(bvdd)"][-1], "bias_ok": wave["v(bias_ok)"][-1],
        "ptat_settled": abs(wave["v(ptat)"][-1] - interp(t, wave["v(ptat)"], tb)),
        "ctat_settled": abs(wave["v(ctat)"][-1] - interp(t, wave["v(ctat)"], tb)),
    }
    fails = [k for k, (lo, hi) in WINDOWS.items() if not (lo <= m[k] <= hi)]
    return {"status": "pass" if not fails else "fail", "m": m, "fails": fails}


ORIG = {  # the six issue-#86 points: (record file, scenario) and the originally recorded failure (ee63b45, dirty tree)
    "en-high": ("sim/temp-core-startup/records/20260826-053032-ee63b45.json", "temp-core-startup"),
    "en-delayed": ("sim/temp-core-startup-en-delayed/records/20260826-054047-ee63b45.json", "temp-core-startup-en-delayed"),
}


def load_results(run_dir):
    """{combo: {'report': dict|None, 'points': {cid: graded}}} -- graded from the retrieved waveforms."""
    out = {}
    for scen in SCENARIOS:
        for var in VARIANTS:
            combo = f"{scen}__{var}"
            rp = run_dir / combo / "report.json"
            ent = {"scenario": scen, "variant": var, "report": None, "points": {}, "refusal": None}
            if sim_common.report_usable(rp):
                rep = json.loads(rp.read_text())
                ent["report"] = rep
                for c in rep["corners"]:
                    cid = corner_id(c["process"], c["temperature_c"], c["supply_v"]["vset"])
                    try:
                        w = sim_common.load_wave(c["artifacts"]["waveform"])
                        g = grade_wave(w, scen, var)
                    except (ValueError, OSError, KeyError) as err:
                        g = {"status": "nonconverged", "reason": f"waveform unreadable: {err}"}
                    g["klt_status"] = c.get("status")
                    g["log"] = c["artifacts"].get("log")
                    g["deck"] = c["artifacts"].get("deck")
                    ent["points"][cid] = g
            else:
                try:
                    ent["refusal"] = json.loads((run_dir / combo / "klt.stderr").read_text() or "{}").get("error", {})
                except (OSError, json.JSONDecodeError):
                    ent["refusal"] = {"message": "no usable report", "code": "unknown"}
                if not ent["refusal"]:
                    # klt writes the error envelope on stdout (report.json) or stderr depending on version
                    try:
                        ent["refusal"] = json.loads((run_dir / combo / "report.json").read_text()).get("error", {})
                    except (OSError, json.JSONDecodeError):
                        ent["refusal"] = {"message": "no report", "code": "unknown"}
            out[combo] = ent
    return out


def nonphysical(m):
    """The README rule-4 signature: negative supply current or a loop node outside the rails (+1 V)."""
    if not m:
        return None
    return m["isup"] <= 0 or not (-1.0 <= m["na"] <= 4.7) or not (-1.0 <= m["nb"] <= 4.7) \
        or not (-1.0 <= m["ptat"] <= 4.7) or not (-1.0 <= m["ctat"] <= 4.7)


def matrix_context(res):
    """Matrix-level evidence per scenario, stated only as far as the variants that actually ran support it."""
    ctx = {}
    for scen in SCENARIOS:
        ran = [v for v in VARIANTS if res[f"{scen}__{v}"]["report"] is not None]
        failsets = {v: sorted(c for c, g in res[f"{scen}__{v}"]["points"].items() if g["status"] != "pass") for v in ran}
        count = {}
        for v, cs in failsets.items():
            for c in cs:
                count.setdefault(c, []).append(v)
        ctx[scen] = {
            "variants_run": ran,
            "failing_sets": failsets,
            # only meaningful with >= 2 variants run
            "failing_sets_pairwise_disjoint": (all(len(vs) == 1 for vs in count.values()) if len(ran) >= 2 else None),
            "repeats_within_scenario": {c: vs for c, vs in sorted(count.items()) if len(vs) > 1},
            "all_failures_nonphysical": all(nonphysical(g.get("m")) for v in ran for g in res[f"{scen}__{v}"]["points"].values()
                                            if g["status"] == "fail") and not any(
                g["status"] == "nonconverged" for v in ran for g in res[f"{scen}__{v}"]["points"].values()),
        }
    return ctx


def repeats_across_combos(res):
    """{corner: [combo, ...]} for every PVT corner that fails in more than one combo (any scenario)."""
    seen = {}
    for combo, ent in res.items():
        for cid, g in ent["points"].items():
            if g["status"] != "pass":
                seen.setdefault(cid, []).append(combo)
    return {c: cs for c, cs in sorted(seen.items()) if len(cs) > 1}


def base_caveat(res):
    st = "ran" if res["en-high__base"]["report"] is not None else "was NOT run (fleet refusal)"
    return ("`base`, and with it every variant in this sweep, re-expresses the original deck's supply source (behavioural "
            "`BVDD` = swept `VSET` x unit PWL ramp instead of the original `V1` PWL source), so the six points not recurring here "
            "is also consistent with a deck/supply-source difference and is not by itself proof of a solver artifact; the control "
            f"that would tie the original failures to the old deck is the EN-high `base` combo, which {st}")


def verdict_for_point(cid, scen, res, ctx=None):
    """Per-point verdict from the variant outcomes at one (scenario, corner)."""
    ctx = ctx or matrix_context(res)
    rows = {}
    for var in VARIANTS:
        g = res[f"{scen}__{var}"]["points"].get(cid)
        rows[var] = g
    ran = {v: g for v, g in rows.items() if g is not None}
    passes = {v: g for v, g in ran.items() if g["status"] == "pass"}
    fails = {v: g for v, g in ran.items() if g["status"] != "pass"}
    np_fails = {v: g for v, g in fails.items() if g["status"] == "fail" and nonphysical(g["m"])}
    # physical-branch agreement: all passing variants must agree on PTAT/CTAT (a single stable branch)
    ptats = [g["m"]["ptat"] for g in passes.values()]
    spread = (max(ptats) - min(ptats)) if len(ptats) >= 2 else None  # None = not assessed (< 2 physical landings)
    if not ran:
        v, why = "NOT-RUN", "no variant produced a result for this point (fleet refusal)"
    elif not passes:
        v, why = "REAL-FAILURE", "fails in every variant that ran; operating point recorded below"
    elif fails and np_fails and len(np_fails) == len(fails):
        v, why = "SOLVER-ARTIFACT", ("fails (non-physical signature) in "
                                     + ",".join(np_fails) + " and lands on the physical branch in " + ",".join(passes))
    elif fails:
        v, why = "MIXED", "fails in " + ",".join(fails) + " without the non-physical signature; needs a look"
    else:
        v = "NOT-REPRODUCED"
        sc = ctx[scen]
        nrun = len(sc["variants_run"])
        if nrun >= 2:
            disj = sc["failing_sets_pairwise_disjoint"]
            mtx = (f"the matrix-level checks across the {nrun} {scen} variants run ({', '.join(sc['variants_run'])}): the failing sets "
                   + ("differ between those variants and no point fails in more than one of them"
                      if disj else "differ between those variants, but some points fail in more than one of them (listed under Repeats)")
                   + (", every failure is non-physical, and " if sc["all_failures_nonphysical"]
                      else ", NOT every failure is non-physical (see the matrix table), and "))
            if len(passes) >= 2:
                mtx += f"physical-branch landings at this point agree to {spread:.2g} V"
            else:
                mtx += "physical-branch agreement at this point is not assessed (fewer than 2 landings)"
        else:
            mtx = ("the observation that " + ("every failure" if sc["all_failures_nonphysical"] else "NOT every failure")
                   + f" in the {nrun} {scen} variant run ({', '.join(sc['variants_run'])}) is non-physical; cross-variant checks "
                   f"(whether the failing set moves with the setting, physical-branch agreement) are not assessed ({nrun} variant)")
        why = (f"passes on the physical branch in all {len(ran)} variant(s) run ({', '.join(ran)}); the `base` deck "
               + ("was among them" if "base" in ran else "was NOT run for this scenario (fleet refusal)")
               + ". The original non-physical landing did not recur at this point, so the artifact explanation is NOT demonstrated at this point itself. "
               "What supports it is limited to " + mtx + ". Caveat: " + base_caveat(res) + ". No real failure was observed here")
    return {"verdict": v, "why": why, "n_variants_run": len(ran), "n_pass": len(passes), "ptat_spread_across_passing_V": spread,
            "variants": {k: (None if g is None else {"status": g["status"], **({"m": g["m"]} if "m" in g else {"reason": g.get("reason")})})
                         for k, g in rows.items()}}


def cmd_record(args):
    run_dir = BUILD / args.run_id
    meta = json.loads((run_dir / "run.json").read_text())
    # Headline provenance = the LATEST invocation of this run (a run.json whose first
    # invocation predates a client upgrade or carried an uncommitted driver edit would
    # otherwise headline a state that submitted nothing). Every invocation's own state
    # is still rendered in the resume list below -- nothing is dropped or rewritten.
    last = meta.get("resumes", [None])[-1] or meta
    git = last["git"]
    klt_client = last.get("klt_client", meta["klt_client"])
    res = load_results(run_dir)
    now = datetime.now(timezone.utc)
    rid = f"{now:%Y%m%d-%H%M%S}-{git['sha']}"
    rec_dir = SIM_DIR / SLUG
    for d in ("records", "netlist-snapshots", "corners"):
        (rec_dir / d).mkdir(exist_ok=True)
    if (rec_dir / "records" / f"{rid}.md").exists():
        sys.exit(f"refusing to overwrite record {rid}")
    snap = rec_dir / "netlist-snapshots" / rid
    snap.mkdir()
    cdir = rec_dir / "corners" / rid
    cdir.mkdir()
    for combo, ent in res.items():
        nl = run_dir / combo / "netlist.spice"
        if nl.is_file():
            (snap / f"{combo}.spice").write_text(sim_common.scrub(nl.read_text(), run_dir, REPO_ROOT))
        (cdir / combo).mkdir()
        for cid, g in ent["points"].items():
            parts = [f"corner {cid}  combo {combo}  verdict-input status={g['status']}"]
            if "m" in g:
                parts.append("graded: " + "; ".join(f"{k}={v:.6g}" for k, v in g["m"].items()) + f"  fails={g['fails']}")
            else:
                parts.append("graded: " + g.get("reason", ""))
            for key, tag in (("deck", "deck"), ("log", "ngspice log")):
                pth = g.get(key)
                if pth and Path(pth).is_file():
                    parts.append(f"--- {tag} ---\n" + sim_common.scrub(Path(pth).read_text(), run_dir, REPO_ROOT))
            (cdir / combo / f"{cid}.log").write_text("\n".join(parts) + "\n")

    # ---- per-scenario full-matrix summaries
    summary = {}
    for combo, ent in res.items():
        if ent["report"] is None:
            summary[combo] = {"status": "NOT-RUN", "refusal": ent["refusal"]}
            continue
        pts = ent["points"]
        bad = {c: g for c, g in pts.items() if g["status"] != "pass"}
        remote = ent["report"]["environment"].get("remote", {})
        summary[combo] = {
            "status": "ran", "n_points": len(pts), "n_pass": len(pts) - len(bad),
            "failing": {c: {"status": g["status"], "nonphysical": nonphysical(g.get("m")), "fails": g.get("fails"),
                            **({k: g["m"][k] for k in ("ptat", "ctat", "na", "nb", "isup")} if "m" in g else {"reason": g.get("reason")})}
                        for c, g in sorted(bad.items())},
            "fleet": {k: remote.get(k) for k in ("job_id", "instance_type", "lifecycle", "runner_klt_version", "client_klt_version", "elapsed_seconds")},
            "ngspice_engine_version": ent["report"]["environment"].get("engine_version"),
        }

    # ---- physical-branch stability across ALL 45 points: passing variants must agree per point
    stab = {}
    for scen in SCENARIOS:
        worst, n_cmp = (0.0, None), 0
        for p, t, v in grid():
            cid = corner_id(p, t, v)
            vals = [res[f"{scen}__{x}"]["points"][cid]["m"]["ptat"] for x in VARIANTS
                    if cid in res[f"{scen}__{x}"]["points"] and res[f"{scen}__{x}"]["points"][cid]["status"] == "pass"]
            n_cmp += len(vals) > 1
            if len(vals) > 1 and max(vals) - min(vals) >= worst[0]:
                worst = (max(vals) - min(vals), cid)
        # None = not assessed: no point had >= 2 variants landing on the physical branch (e.g. only 1 variant ran)
        stab[scen] = {"max_ptat_spread_between_passing_variants_V": worst[0] if n_cmp else None, "at": worst[1],
                      "n_points_compared": n_cmp}

    # ---- the six points
    ctx = matrix_context(res)
    repeats = repeats_across_combos(res)
    not_run = [c for c, s_ in summary.items() if s_["status"] == "NOT-RUN"]
    six = {}
    for scen, cids in SIX.items():
        orec = json.loads((REPO_ROOT / ORIG[scen][0]).read_text())
        for cid in cids:
            oc = next(c for c in orec["corners"] if c["corner_id"] == cid)
            om = {m["name"]: m.get("value") for m in oc["measurements"]}
            vd = verdict_for_point(cid, scen, res, ctx)
            vd["original"] = {"record": ORIG[scen][0], "values": om}
            six[f"{scen}:{cid}"] = vd

    # ---- every failure anywhere has the non-physical signature, and passes somewhere else?
    all_fail = []
    for combo, ent in res.items():
        for cid, g in ent["points"].items():
            if g["status"] != "pass":
                other = [v for v in VARIANTS if f"{ent['scenario']}__{v}" != combo
                         and res[f"{ent['scenario']}__{v}"]["points"].get(cid, {}).get("status") == "pass"]
                all_fail.append({"combo": combo, "corner": cid, "status": g["status"], "nonphysical": nonphysical(g.get("m")), "passes_in": other})
    sig_all = all(f["nonphysical"] for f in all_fail if f["status"] == "fail")
    rec = {
        "record_id": rid, "experiment": SLUG, "issue": 86, "timestamp": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "git": git, "klt": klt_client, "backend": meta["klt_sim_backend_env"], "run_id": args.run_id,
        "windows": WINDOWS, "variants": {k: {"options": v[0], "tramp_s": v[1]} for k, v in VARIANTS.items()},
        "summary": summary, "stability": stab, "six_points": six, "all_failures": all_fail,
        "all_failures_nonphysical_signature": sig_all,
        "matrix_context": ctx, "repeats_across_combos": repeats,
        "repeats_cross_scenario": {c: cs for c, cs in repeats.items() if len({x.split("__")[0] for x in cs}) > 1},
        "not_run_combos": not_run, "acceptance": "partial" if not_run else "complete",
        "caveats": [base_caveat(res)], "resumes": meta.get("resumes", []),
        "supersedes": args.supersedes or "(none)",
        "author": cr.default_author(),
    }
    (rec_dir / "records" / f"{rid}.json").write_text(json.dumps(rec, indent=2, default=str) + "\n")

    L = [f"# Record {rid}", "",
         f"- **Record ID**: {rid}",
         f"- **Experiment**: `{SLUG}` -- solver / ramp-rate discrimination of the six temp_core cold-start FAILs (issue #86)",
         "- **Claim**: NOT a spec claim. Decides, per point, whether each of the six Overall-FAIL points of `sim/temp-core-startup/` and `sim/temp-core-startup-en-delayed/` (record `ee63b45`, dirty tree) is a solver artifact (non-physical branch landing that moves with integration settings) or a real failure, by re-running the FULL 45-point PVT matrix under five solver/ramp variants for each of the two EN scenarios and checking the physicality guards (isup > 0, loop nodes inside the rails +1 V) and the unchanged `experiment.json` windows.",
         "- **Netlist provenance**: schematic-derived committed `design/netlist/{bias_core,temp_core}.spice` (unchanged since the `ee63b45` records; `git diff ee63b45 HEAD -- design/netlist/` is empty) in a generated testbench (see `netlist-snapshots/%s/`)" % rid,
         "- **PDK**: sky130A @ open_pdks `c6d73a35f524070e85faff4a6a9eef49553ebc2b` (matches sim/pdk.json pin), models `libs.tech/combined/sky130.lib.spice` (sha256 48de7c67...)",
         f"- **Tools**: {klt_client} (client); fleet ngspice-{next((s.get('ngspice_engine_version') for s in summary.values() if s.get('ngspice_engine_version')), '?')} on Spot `c7i/m7i.4xlarge`, fleet runner klt 0.5.0 (version mismatch warning from the client, reported per job below); backend `{meta['klt_sim_backend_env']}`",
         f"- **Repo state**: `{git['sha']}` on `{git['branch']}` (working tree {'DIRTY' if git['dirty'] else 'clean'} at run time)"
         + "".join(f"; resumed {r['started_utc']} at `{r['git']['sha']}` (working tree {'DIRTY' if r['git']['dirty'] else 'clean'})" for r in meta.get("resumes", [])),
         f"- **Coverage**: {10 - len(not_run)} of 10 (scenario, variant) combos ran" + (f"; NOT-RUN (fleet refusal): {', '.join(not_run)}. This record is PARTIAL and does not by itself complete issue #86" if not_run else ""),
         "- **Corner matrix run**: process tt, ss, ff, sf, fs x -40/27/125 C x 2.97/3.30/3.63 V = 45 points per (scenario, variant); a combo that the fleet refused is listed as NOT-RUN below, never substituted locally",
         "- **Statistical convention**: N/A (corner-matrix check)",
         "", "## Variants", "",
         "| variant | `.options` | supply ramp time |", "|---|---|---|"]
    for k, v in VARIANTS.items():
        L.append(f"| `{k}` | `{v[0]}` | {v[1]*1e6:g} us |")
    L += ["", "`base` is the deck of the `ee63b45` records re-expressed for `klt sim` (the supply is a behavioural source equal to the original PWL ramp scaled by klt's swept `VSET`; this is a different realisation of the same circuit, so a changed failing set under `base` is itself a solver-sensitivity datum, not a reproduction).", "",
          "Caveat: " + base_caveat(res) + ".", "",
          "## Full-matrix outcome per (scenario, variant)", "", "| combo | result | failing points (PVT corner: ptat / isup / signature) |", "|---|---|---|"]
    for combo, s in summary.items():
        if s["status"] == "NOT-RUN":
            L.append(f"| {combo} | NOT-RUN: fleet refused ({s['refusal'].get('code')}) | - |")
        else:
            f = "; ".join(f"`{c}`: {d.get('ptat', float('nan')):.3g} V / {d.get('isup', float('nan')):.3g} A / {'non-physical' if d['nonphysical'] else 'physical-but-out-of-window'}" for c, d in s["failing"].items()) or "none"
            L.append(f"| {combo} | {s['n_pass']}/{s['n_points']} PASS | {f} |")
    L += ["", "Fleet jobs (`environment.remote`): " + ", ".join(f"{c}={s['fleet']['job_id']}" for c, s in summary.items() if s["status"] == "ran"), "",
          "## Physical-branch stability (all 45 points, passing variants only)", ""]
    for scen, d in stab.items():
        if d["max_ptat_spread_between_passing_variants_V"] is None:
            L.append(f"- {scen}: not assessed ({len(ctx[scen]['variants_run'])} variant run; no point has two physical-branch landings to compare)")
        else:
            L.append(f"- {scen}: largest PTAT spread between variants that landed on the physical branch = {d['max_ptat_spread_between_passing_variants_V']:.3g} V (at `{d['at']}`, over {d['n_points_compared']} points with >= 2 landings)")
    L += ["", f"Every FAIL anywhere in the sweep has the non-physical signature (isup <= 0 or a node outside the rails +1 V): **{sig_all}**.", "",
          "## Does the failing set move with the setting?", ""]
    for scen in SCENARIOS:
        sc = ctx[scen]
        if len(sc["variants_run"]) < 2:
            L.append(f"- {scen}: not assessed ({len(sc['variants_run'])} variant run: {', '.join(sc['variants_run']) or 'none'})")
        else:
            L.append(f"- {scen} (across the {len(sc['variants_run'])} variants run: {', '.join(sc['variants_run'])}): failing sets "
                     + ("are pairwise disjoint (no point fails in more than one of these variants)" if sc["failing_sets_pairwise_disjoint"]
                        else "overlap at " + ", ".join(f"`{c}` ({', '.join(v)})" for c, v in sc["repeats_within_scenario"].items())))
    L += ["", "## Repeats (PVT corners failing in more than one combo)", ""]
    if repeats:
        for c, cs in repeats.items():
            scens = sorted({x.split("__")[0] for x in cs})
            L.append(f"- `{c}`: fails in {', '.join(cs)} ({'cross-scenario' if len(scens) > 1 else 'within ' + scens[0]})")
        rep_np = all(nonphysical(res[x]["points"][c].get("m")) for c, cs in repeats.items() for x in cs)
        L.append("- Recorded as observed. " + ("Every repeated failure carries the non-physical signature, so the repeats do not "
                 "by themselves indicate a real failure; they do mean the failures are not fully scattered at random across the matrix "
                 "and should be rechecked when the NOT-RUN combos run." if rep_np else
                 "Some repeated failures do NOT carry the non-physical signature; those points need a look."))
    else:
        L.append("- none")
    L += ["",
          "## Per-point verdict for the six issue points", ""]
    for key, d in six.items():
        scen, cid = key.split(":")
        ov = d["original"]["values"]
        L += [f"### {scen} `{cid}`: **{d['verdict']}**", "",
              f"- Original (`ee63b45`, dirty): ptat={ov.get('ptat')} V, ctat={ov.get('ctat')} V, isup={ov.get('isup')} A",
              f"- {d['why']}",
              f"- variants run: {d['n_variants_run']}, physical-branch landings: {d['n_pass']}; PTAT spread across the passing variants: {('%.3g V' % d['ptat_spread_across_passing_V']) if d['ptat_spread_across_passing_V'] is not None else 'not assessed (' + str(d['n_pass']) + ' landing)'}", "",
              "| variant | PVT corner | status | ptat (V) | ctat (V) | isup (A) | na / nb (V) |", "|---|---|---|---|---|---|---|"]
        for var, g in d["variants"].items():
            if g is None:
                L.append(f"| {var} | {cid} | NOT-RUN | | | | |")
            elif "m" in g:
                m = g["m"]
                L.append(f"| {var} | {cid} | {g['status']} | {m['ptat']:.5g} | {m['ctat']:.5g} | {m['isup']:.4g} | {m['na']:.4g} / {m['nb']:.4g} |")
            else:
                L.append(f"| {var} | {cid} | {g['status']}: {g.get('reason')} | | | | |")
        L.append("")
    L += ["## Links", "", f"- driver: `sim/{SLUG}/run_solver_sweep.py`; json twin `records/{rid}.json`; netlists `netlist-snapshots/{rid}/`; per-point logs `corners/{rid}/<scenario>__<variant>/<corner>.log`",
          "- windows are copied unchanged from the two `experiment.json` files (no relaxation)", "",
          f"- **Timestamp**: {rec['timestamp']}", f"- **Author**: {rec['author']}",
          f"- **Supersedes**: {rec['supersedes'] if rec['supersedes'] != '(none)' else '(none)'}"
          + (f" -- completes its 10-of-10 combo coverage; that record is untouched and remains the evidence for its own run" if args.supersedes else " -- adds evidence next to `ee63b45`; those records are untouched")]
    (rec_dir / "records" / f"{rid}.md").write_text("\n".join(L) + "\n")
    print(rid)
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--run-id")
    r.add_argument("--resume", action="store_true")
    r.add_argument("--scenario", action="append", choices=SCENARIOS)
    r.add_argument("--variant", action="append", choices=list(VARIANTS))
    r.add_argument("--jobs", type=int, default=2)
    r.set_defaults(fn=cmd_run)
    p = sub.add_parser("probe")
    p.add_argument("--run-id", required=True)
    p.add_argument("point", nargs="+", help="scenario:variant:cornerid")
    p.set_defaults(fn=cmd_probe)
    rc = sub.add_parser("record")
    rc.add_argument("--run-id", required=True)
    rc.add_argument("--supersedes", default=None, help="record id this record replaces (append-only: the old record is untouched)")
    rc.set_defaults(fn=cmd_record)
    a = ap.parse_args()
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
