#!/usr/bin/env python3
"""Solver / ramp-rate discrimination sweep for the temp_core cold-start FAILs (issue #86).

Question: are the six Overall-FAIL points in sim/temp-core-startup/ and
sim/temp-core-startup-en-delayed/ (record ee63b45, dirty tree) solver artifacts (a
non-physical branch landing that moves with integration settings) or real failures?

Every (EN scenario x solver/ramp variant) is ONE ``klt sim`` corner request over the FULL
45-point PVT matrix, submitted to the Spot batch fleet with an explicit ``--backend batch``
(sim/README.md rule 6: a solver sweep over only the six points proves little).  This script
never launches ngspice over a grid itself and never falls back to a local grid if the fleet
refuses; refusals are recorded.  ``probe`` runs SINGLE local points only.

Stages:  run | probe | record
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR / "bin"))
import sim_common  # noqa: E402

cr = sim_common.load_corner_run()
SLUG = "temp-core-startup-solver"
BUILD = REPO_ROOT / "sim" / "build" / SLUG
MODEL_LIB = "libs.tech/combined/sky130.lib.spice"
say = sim_common.say

PROCS = ["tt", "ss", "ff", "sf", "fs"]
TEMPS = [-40, 27, 125]
SUPPLIES = [2.97, 3.3, 3.63]
TSTOP = 10e-3
STEP = 10e-6

# The six FAIL points the issue names (EN scenario, corner id)
SIX = {
    "en-high": ["tt_-40c_3.30v", "tt_125c_3.30v", "ff_-40c_3.30v"],
    "en-delayed": ["tt_27c_3.63v", "tt_125c_3.63v", "sf_-40c_2.97v"],
}

# variant -> (.options extra, tramp seconds).  base = the deck of the ee63b45 records.
VARIANTS = {
    "base": ("method=gear trtol=50", 100e-6),
    "trtol7": ("method=gear trtol=7", 100e-6),
    "reltol2e-4": ("method=gear trtol=50 reltol=2e-4", 100e-6),
    "ramp1u": ("method=gear trtol=50", 1e-6),
    "ramp2m": ("method=gear trtol=50", 2e-3),
}
SCENARIOS = ["en-high", "en-delayed"]

# Measurement windows: copied from the existing experiment.json files (NOT relaxed).
WINDOWS = {
    "ptat": (0.3, 2.6), "ctat": (0.2, 1.1), "na": (-1.0, 4.7), "nb": (-1.0, 4.7),
    "isup": (1e-8, 5e-5), "bias_ok": (2.0, 3.7), "ptat_settled": (0.0, 1e-3), "ctat_settled": (0.0, 1e-3),
}


def corner_id(p, t, v):
    return f"{p}_{cr.fmt_temp(t)}c_{v:.2f}v"


def grid():
    return [(p, t, v) for p in PROCS for t in TEMPS for v in SUPPLIES]


def subckt_text(name):
    txt = (REPO_ROOT / "design" / "netlist" / f"{name}.spice").read_text()
    return "\n".join(ln for ln in txt.splitlines() if ln.strip().lower() != ".end") + "\n"


def build_netlist(scenario, variant):
    opts, tramp = VARIANTS[variant]
    ten_start = tramp + 200e-6
    ten_end = ten_start + 50e-6
    en_node = "VDD" if scenario == "en-high" else "EN"
    lines = [
        f"* {SLUG} ({scenario}, {variant}): generated by sim/{SLUG}/run_solver_sweep.py -- do not edit",
        "* Same circuit/topology as sim/temp-core-startup{,-en-delayed}/testbench (V1 PWL ramp 0->vsup over tramp;",
        "* XBIAS + XDUT; EN tied to VDD or released after the supply is up). VDD is a behavioural source equal",
        "* to that PWL ramp, driven from klt's swept VSET source. DUT = committed design/netlist/{bias,temp}_core.spice.",
        f".param tramp={tramp:.9g}",
        f".param ten_start={ten_start:.9g}",
        f".param ten_end={ten_end:.9g}",
        f".param tstop={TSTOP:.9g}",
        f".options wnflag=1 {opts}",
        "* ng_nomodcheck: same as sim/spiceinit; carried in the netlist because the fleet runner ignores options.ngspice_init",
        ".control", "set ng_nomodcheck", ".endc",
        "VSET vsetn 0 3.3",
        "* unit PWL ramp keeps the exact breakpoint at tramp that the original V1 PWL source had; BVDD scales it by the swept VSET",
        "VRAMP rampn 0 PWL(0 0 {tramp} 1 {tstop} 1)",
        "BVDD VDD 0 V = v(vsetn)*v(rampn)",
    ]
    if scenario == "en-delayed":
        lines += ["VENR enrampn 0 PWL(0 0 {ten_start} 0 {ten_end} 1 {tstop} 1)", "BEN EN 0 V = v(vsetn)*v(enrampn)"]
    lines += [
        "XBIAS VDD 0 IBIAS VREF BIAS_OK bias_core",
        f"XDUT VDD 0 IBIAS {en_node} PTAT CTAT temp_core",
        "",
        subckt_text("bias_core"),
        subckt_text("temp_core"),
        ".end",
    ]
    return "\n".join(lines) + "\n"


def build_request(backend, corners=None, timeout=3000):
    p, t, v = (corners or (PROCS, TEMPS, SUPPLIES))
    req = {
        "netlist": "netlist.spice",
        "backend": backend,
        "models": {"pdk": "sky130A", "lib": MODEL_LIB},
        "corners": {"process": p, "supply_v": {"vset": v}, "temperature_c": t},
        "analysis": {"kind": "tran", "args": f"{STEP:.6g} {TSTOP:.6g} uic"},
        "measurements": [{"name": "vdd_end", "spice": f".meas tran vdd_end FIND v(vdd) AT={TSTOP:.6g}", "unit": "V"}],
        "options": {"timeout_s": timeout, "keep_artifacts": True, "waveforms": True},
    }
    if backend == "batch":
        req["batch"] = {"runner_version_check": "warn"}
    return req


def klt_version():
    p = subprocess.run(["klt", "--version"], capture_output=True, text=True)
    return (p.stdout.strip() or p.stderr.strip())


def cmd_run(args):
    now = datetime.now(timezone.utc)
    git = cr.git_state()
    run_id = args.run_id or f"{now:%Y%m%d-%H%M%S}-{git['sha']}"
    run_dir = BUILD / run_id
    run_dir.mkdir(parents=True, exist_ok=args.resume)
    combos = [(s, v) for s in (args.scenario or SCENARIOS) for v in (args.variant or list(VARIANTS))]
    meta = {"run_id": run_id, "started_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"), "klt_client": klt_version(),
            "klt_sim_backend_env": os.environ.get("KLT_SIM_BACKEND"), "git": git, "combos": combos}
    (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")

    def one(sv):
        s, v = sv
        name = f"{s}__{v}"
        d = run_dir / name
        if sim_common.report_usable(d / "report.json"):
            return {"combo": name, "skipped": "usable report exists"}
        d.mkdir(parents=True, exist_ok=True)
        (d / "netlist.spice").write_text(build_netlist(s, v))
        (d / "request.json").write_text(json.dumps(build_request("batch"), indent=2) + "\n")
        say(f"[submit] {name}: 45 points -> batch fleet")
        p = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "batch", "-o", str(d / "out"), "--format", "json"],
                           capture_output=True, text=True, timeout=4 * 3600)
        (d / "report.json").write_text(p.stdout)
        (d / "klt.stderr").write_text(p.stderr)
        try:
            st = json.loads(p.stdout).get("status", "?")
        except json.JSONDecodeError:
            st = "NO-JSON"
        say(f"[done]   {name}: exit {p.returncode}, status {st}")
        return {"combo": name, "exit": p.returncode, "status": st}

    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, args.jobs)) as ex:
        for f in [ex.submit(one, c) for c in combos]:
            try:
                results.append(f.result())
            except Exception as err:  # noqa: BLE001 -- recorded
                results.append({"error": repr(err)})
                say(f"[error] {err!r}")
    meta["submit_results"] = results
    (run_dir / "run.json").write_text(json.dumps(meta, indent=2) + "\n")
    print(f"raw outputs: {run_dir}")
    return 0


def parse_cid(cid):
    p, t, v = cid.split("_")
    return p, int(t[:-1]), float(v[:-1])


def cmd_probe(args):
    """Single-corner LOCAL probes (never a grid)."""
    run_dir = BUILD / args.run_id
    for item in args.point:
        scen, variant, cid = item.split(":")
        p, t, v = parse_cid(cid)
        d = run_dir / "probe" / f"{scen}__{variant}__{cid}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "netlist.spice").write_text(build_netlist(scen, variant))
        req = build_request("local", ([p], [t], [v]))
        (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
        say(f"[probe] local single corner {scen} {variant} {cid}")
        pr = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "local", "-o", str(d / "out"), "--format", "json"],
                            capture_output=True, text=True, timeout=3600)
        (d / "report.json").write_text(pr.stdout)
        (d / "klt.stderr").write_text(pr.stderr)
        say(f"[probe] exit {pr.returncode}")
    return 0


def interp(t, y, tq):
    import bisect
    i = bisect.bisect_left(t, tq)
    if i <= 0:
        return y[0]
    if i >= len(t):
        return y[-1]
    f = (tq - t[i - 1]) / (t[i] - t[i - 1])
    return y[i - 1] + f * (y[i] - y[i - 1])


def grade_wave(wave, scenario, variant):
    """Same quantities and windows as the experiment.json measurements, read from the saved waveform."""
    import math
    t = wave.get("time", [])
    need = ["v(ptat)", "v(ctat)", "v(xdut.na)", "v(xdut.nb)", "i(bvdd)", "v(bias_ok)"]
    miss = [n for n in need if n not in wave]
    if len(t) < 20 or miss:
        return {"status": "nonconverged", "reason": f"waveform short/missing (n={len(t)}, missing={miss})"}
    if any((not math.isfinite(x)) for n in need for x in wave[n]):
        return {"status": "nonconverged", "reason": "non-finite samples"}
    if t[-1] < TSTOP * 0.999:
        return {"status": "nonconverged", "reason": f"ended at {t[-1]:.4g}s < tstop"}
    te, tb = t[-1], t[-1] - 1e-3
    m = {
        "ptat": wave["v(ptat)"][-1], "ctat": wave["v(ctat)"][-1],
        "na": wave["v(xdut.na)"][-1], "nb": wave["v(xdut.nb)"][-1],
        "isup": -wave["i(bvdd)"][-1], "bias_ok": wave["v(bias_ok)"][-1],
        "ptat_settled": abs(wave["v(ptat)"][-1] - interp(t, wave["v(ptat)"], tb)),
        "ctat_settled": abs(wave["v(ctat)"][-1] - interp(t, wave["v(ctat)"], tb)),
    }
    fails = [k for k, (lo, hi) in WINDOWS.items() if not (lo <= m[k] <= hi)]
    return {"status": "pass" if not fails else "fail", "m": m, "fails": fails}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("--run-id")
    r.add_argument("--resume", action="store_true")
    r.add_argument("--scenario", action="append", choices=SCENARIOS)
    r.add_argument("--variant", action="append", choices=list(VARIANTS))
    r.add_argument("--jobs", type=int, default=2)
    r.set_defaults(fn=cmd_run)
    p = sub.add_parser("probe")
    p.add_argument("--run-id", required=True)
    p.add_argument("point", nargs="+", help="scenario:variant:cornerid")
    p.set_defaults(fn=cmd_probe)
    a = ap.parse_args()
    return a.fn(a)


if __name__ == "__main__":
    sys.exit(main())
