#!/usr/bin/env python3
"""Driver for the por_comparator VPOR-up / VPOR-down / hysteresis campaign (issue #102).

The process x temperature grid is expressed as ``klt sim`` requests (one request
per sweep rate and bias variant; process and temperature are klt's own corner
axes) and goes to the Spot batch fleet.  This script never launches ngspice over
a grid itself.  The sweep-rate axis is a ``.param rate`` written into one
generated netlist per request, not an extension of sim/bin/corner-run.py.

Stages (each is a subcommand):

  run      build netlists + requests, submit them to the fleet (explicit
           ``--backend batch``); raw outputs stay under sim/build/.
  probe    ONE single-corner LOCAL run (``--backend local``): a debug probe /
           cross-check of the fleet result; never a grid.
  record   extract the edges from every retrieved waveform
           (threshold_extractor.py) and write the append-only evidence:
           netlist snapshots, per-point logs, change-triggered traces,
           markdown + JSON record.
  selftest run the extractor on synthetic sweeps with known answers.

A batch submit failure is reported in the record; there is no local fallback.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import functools
import gzip
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE.parent
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR / "bin"))
sys.path.insert(0, str(HERE))

import sim_common  # noqa: E402
import threshold_extractor as tx  # noqa: E402

cr = sim_common.load_corner_run()

SLUG = "por-comparator-thresholds"
MANIFEST = HERE / "experiment.json"
BUILD = REPO_ROOT / "sim" / "build" / SLUG
NETLIST_DIR = REPO_ROOT / "design" / "netlist"
MODEL_LIB = "libs.tech/combined/sky130.lib.spice"


say = sim_common.say
rate_tag = sim_common.rate_tag
scrub = functools.partial(sim_common.scrub, repo_root=REPO_ROOT)


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def corner_id(proc: str, temp: float) -> str:
    return f"{proc}_{cr.fmt_temp(temp)}c"


AXES = ("main", "passive-skew")


def processes(man: dict, axis: str) -> list[str]:
    """Process sections of one corner axis.  'main' = the 5 MOS corners (the issue's 5x3 grid);
    'passive-skew' = the ll/hh resistor/capacitor sections (tt MOS), a separately-recorded supplement."""
    return man["corners"]["process"] if axis == "main" else man["corners"]["passive_skew"]["process"]


def all_rates(man: dict) -> list[tuple[float, float | None]]:
    """[(rate, primary_or_None)]: each primary rate followed by its half-rate guard."""
    f = man["rates"]["half_rate_guard_factor"]
    out = []
    for r in man["rates"]["primary_v_per_s"]:
        out += [(r, None), (r * f, r)]
    return out


def tstop_for(rate: float, man: dict) -> float:
    return 2 * man["sweep"]["peak_v"] / rate


# --------------------------------------------------------------------------
# netlists and requests
# --------------------------------------------------------------------------


def tb_netlist_head(variant: dict, run_dir: Path, pdk) -> str:
    """Netlist the variant's testbench schematic with xschem; keep only the testbench part."""
    produced = cr.netlist_with_xschem(HERE / variant["schematic"], run_dir / "tb" / variant["schematic"].split("/")[-1][:-4], pdk)
    text = produced.read_text().replace(str(REPO_ROOT) + os.sep, "")
    head = text.split("\n* expanding")[0]
    return "\n".join(ln for ln in head.splitlines() if ln.strip().lower() != ".end") + "\n"


def build_netlist(head: str, variant: dict, rate: float) -> str:
    dut = ""
    for name in variant["dut_netlists"]:
        # bare name = design/netlist export; a path with "/" is repo-relative (post-layout extracted DUT, issue #124)
        txt = ((REPO_ROOT / name) if "/" in name else (NETLIST_DIR / name)).read_text()
        dut += "\n".join(ln for ln in txt.splitlines() if ln.strip().lower() != ".end") + "\n"
    banner = (
        f"* {SLUG}: generated by sim/{SLUG}/run_thresholds_campaign.py -- do not edit\n"
        f"* sweep rate (V/s, up and down): {rate:g}\n"
        f".param rate={rate:g}\n"
        "* ng_nomodcheck: same setting as sim/spiceinit; carried in the netlist because the\n"
        "* fleet runner ignores options.ngspice_init (see experiment.json ngspice_note)\n"
        ".control\nset ng_nomodcheck\n.endc\n"
    )
    return banner + head + "\n" + dut


def build_request(rate: float, man: dict, backend: str, corners: dict | None = None, capacity_wait_s: float = 0, axis: str = "main") -> dict:
    sw = man["sweep"]
    tstop = tstop_for(rate, man)
    c = man["corners"]
    req = {
        "netlist": "netlist.spice",
        "backend": backend,
        "models": {"pdk": "sky130A", "lib": MODEL_LIB},
        "corners": corners
        or {
            "process": processes(man, axis),
            "supply_v": {"vset": [sw["peak_v"]]},
            "temperature_c": c["temperature_c"],
        },
        "analysis": {"kind": "tran", "args": f"1u {tstop:.9g} 0 {sw['tmax_s']:.3g}"},
        "measurements": [
            {"name": "vdd_end", "spice": f".meas tran vdd_end FIND v(vdd) AT={tstop - 1e-6:.9g}", "unit": "V"},
            {"name": "por_raw_max", "spice": ".meas tran por_raw_max MAX v(por_raw)", "unit": "V"},
        ],
        "options": {"timeout_s": 1500, "keep_artifacts": True, "waveforms": True},
    }
    if backend == "batch":
        req["batch"] = {"runner_version_check": "warn"}
        if capacity_wait_s:
            req["batch"]["capacity_wait_s"] = capacity_wait_s
    return req


def klt_version() -> str:
    p = subprocess.run(["klt", "--version"], capture_output=True, text=True)
    return p.stdout.strip() or p.stderr.strip()


def submit(variant_name: str, rate: float, head: str, man: dict, run_dir: Path, capacity_wait_s: float, axis: str = "main") -> dict:
    netlist = build_netlist(head, man["variants"][variant_name], rate)
    req = build_request(rate, man, "batch", capacity_wait_s=capacity_wait_s, axis=axis)
    points = len(processes(man, axis)) * len(man["corners"]["temperature_c"])
    return sim_common.submit_request(variant_name, rate, run_dir, netlist, req, f" ({axis})", points)


def cmd_run(args) -> int:
    man = load_manifest()
    pdk = cr.resolve_pdk(cr.load_pin())
    git_info = cr.git_state()
    if git_info["dirty"] and not args.allow_dirty:
        raise SystemExit("working tree is dirty: commit first (records must carry a clean-tree SHA); --allow-dirty is for debugging only")
    now = datetime.now(timezone.utc)
    run_id = args.run_id or f"{now:%Y%m%d-%H%M%S}-{git_info['sha']}"
    run_dir = BUILD / run_id
    if run_dir.exists() and not args.retry_failed:
        raise SystemExit(f"{run_dir} exists; refusing to reuse a run id")
    axis = args.axis
    if args.retry_failed and (run_dir / "run.json").is_file():
        axis = json.loads((run_dir / "run.json").read_text()).get("axis", "main")  # a retry keeps the run's own axis
    run_dir.mkdir(parents=True, exist_ok=True)
    variants = args.variant or [v for v in man["variants"] if not v.endswith("-postlayout")]  # post-layout variants only on explicit --variant
    work = [(v, r) for v in variants for r, _ in all_rates(man)]
    if args.retry_failed:
        work = [(v, r) for v, r in work if not sim_common.report_usable(run_dir / v / rate_tag(r) / "report.json")]
    heads = {v: tb_netlist_head(man["variants"][v], run_dir / ("retry" if args.retry_failed else "."), pdk) for v in variants}
    meta = {
        "run_id": run_id,
        "started_utc": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "variants": variants,
        "axis": axis,
        "process": processes(man, axis),
        "git": git_info,
        "klt_client": klt_version(),
        "klt_sim_backend_env": os.environ.get("KLT_SIM_BACKEND"),
        "work": [[v, r] for v, r in work],
    }
    say(f"run id {run_id}: {len(work)} request(s)")
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(2, args.jobs)) as ex:
        futs = [ex.submit(submit, v, r, heads[v], man, run_dir, args.capacity_wait, axis) for v, r in work]
        for f in futs:
            try:
                results.append(f.result())
            except Exception as err:  # noqa: BLE001 -- recorded, never swallowed
                results.append({"error": repr(err)})
                say(f"[error] submit raised: {err!r}")
    meta["submit_results"] = results
    path = run_dir / ("run.retry.json" if args.retry_failed else "run.json")
    path.write_text(json.dumps(meta, indent=2) + "\n")
    print(f"raw outputs: {run_dir}")
    return 0


def cmd_probe(args) -> int:
    """One single-corner LOCAL run (debug probe / cross-check)."""
    man = load_manifest()
    pdk = cr.resolve_pdk(cr.load_pin())
    variant = args.variant
    rate = args.rate or man["rates"]["primary_v_per_s"][0]
    run_dir = BUILD / (args.run_id or "probe")
    d = run_dir / "probe" / f"{variant}_{rate_tag(rate)}_{args.process}_{cr.fmt_temp(args.temp)}c"
    d.mkdir(parents=True, exist_ok=True)
    head = tb_netlist_head(man["variants"][variant], d, pdk)
    (d / "netlist.spice").write_text(build_netlist(head, man["variants"][variant], rate))
    req = build_request(
        rate, man, "local",
        corners={"process": [args.process], "supply_v": {"vset": [man["sweep"]["peak_v"]]}, "temperature_c": [args.temp]},
    )
    req["options"]["ngspice_init"] = [ln.strip() for ln in (SIM_DIR / "spiceinit").read_text().splitlines() if ln.strip() and not ln.startswith("*")]
    (d / "request.json").write_text(json.dumps(req, indent=2) + "\n")
    say(f"[probe] one local corner {args.process}/{args.temp}C, {rate:g} V/s, variant {variant}")
    p = subprocess.run(["klt", "sim", str(d / "request.json"), "--backend", "local", "-o", str(d / "out"), "--format", "json"], capture_output=True, text=True, timeout=3600)
    (d / "report.json").write_text(p.stdout)
    (d / "klt.stderr").write_text(p.stderr)
    print(f"exit {p.returncode}; report {d / 'report.json'}")
    try:
        rep = json.loads(p.stdout)
        for c in rep.get("corners", []):
            art = c.get("artifacts") or {}
            if art.get("waveform"):
                res = tx.analyze(load_wave(Path(art["waveform"])), man["polarity"]["up"], man["polarity"]["down"])
                print(json.dumps({k: res.get(k) for k in ("verdict", "hysteresis_v", "max_vdd_step_v")}, indent=1))
                print("up:", {k: v for k, v in res["up"].items() if k != "edges"})
                print("down:", {k: v for k, v in res["down"].items() if k != "edges"})
    except Exception as err:  # noqa: BLE001
        print("could not analyze probe:", err)
    return 0


# --------------------------------------------------------------------------
# record
# --------------------------------------------------------------------------


def load_wave(path: Path) -> dict[str, list[float]]:
    opener = gzip.open if str(path).endswith(".gz") else open
    with opener(path, "rt") as fh:
        doc = json.load(fh)
    names = [v["name"] for v in doc["variables"]]
    cols: dict[str, list[float]] = {n: [] for n in names}
    for row in doc["points"]:
        for n, x in zip(names, row):
            cols[n].append(float(x))
    return cols


def write_trace(path: Path, wave: dict, dv: float = 0.002, anchor_s: float = 0.2e-3) -> int:
    """Change-triggered trace (VDD, POR_RAW, VREF, IBIAS): a row whenever a column moved >= dv, or an anchor."""
    cols = [c for c in ("time", "v(vdd)", "v(por_raw)", "v(vref)", "v(ibias)") if c in wave]
    t = wave["time"]
    rows, last = [], None
    for i in range(len(t)):
        cur = [wave[c][i] for c in cols[1:]]
        if last is None or i == len(t) - 1 or any(abs(a - b) >= dv for a, b in zip(cur, last[1])) or t[i] - last[0] >= anchor_s:
            rows.append([t[i]] + cur)
            last = (t[i], cur)
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wt") as fh:
        fh.write(",".join(cols) + "\n")
        for r in rows:
            fh.write(",".join(f"{x:.9g}" for x in r) + "\n")
    return len(rows)


def analyze_variant(variant: str, run_dir: Path, man: dict, corners_dir: Path) -> dict:
    points, requests = [], []
    for rate, primary in all_rates(man):
        tag = rate_tag(rate)
        d = run_dir / variant / tag
        rq = {"rate_v_per_s": rate, "tag": tag, "primary_rate": primary, "tstop_s": tstop_for(rate, man)}
        attempts = []
        for ad in sorted(d.glob("attempt*"), key=lambda p: int(p.name[7:] or 0)):
            body = None
            # klt --format json writes a launch-failure error document to stderr with an empty stdout
            for src in ("report.json", "klt.stderr"):
                try:
                    txt = (ad / src).read_text()
                    body = json.loads(txt[txt.index("{"):]) if "{" in txt else None
                except (json.JSONDecodeError, OSError, ValueError):
                    body = None
                if body:
                    break
            attempts.append(scrub((body.get("error") or {}).get("message") or f"report status {body.get('status')}", run_dir)[:400] if body else "unparseable report")
        if attempts:
            rq["failed_earlier_attempts"] = attempts
        rp = d / "report.json"
        if not rp.is_file():
            rq["outcome"] = "NOT SUBMITTED / no report"
            requests.append(rq)
            continue
        try:
            rep = json.loads(rp.read_text())
        except json.JSONDecodeError:
            rq["outcome"] = "NO JSON (klt failed before a report existed): " + scrub((d / "klt.stderr").read_text()[-600:], run_dir)
            requests.append(rq)
            continue
        if "corners" not in rep:
            rq["outcome"] = "klt error (no corners reported): " + scrub(str((rep.get("error") or {}).get("message", rep))[:500], run_dir)
            requests.append(rq)
            continue
        remote = (rep.get("environment") or {}).get("remote") or {}
        rq.update(
            outcome=rep.get("status"), job_id=remote.get("job_id"), instance_type=remote.get("instance_type"),
            lifecycle=remote.get("lifecycle"), runner_klt_version=remote.get("runner_klt_version"),
            elapsed_seconds=remote.get("elapsed_seconds"), state=remote.get("state"), corner_count=rep.get("corner_count"),
        )
        requests.append(rq)
        for c in rep["corners"]:
            proc, temp = c["process"], c["temperature_c"]
            cid = corner_id(proc, temp)
            art = c.get("artifacts") or {}
            log_text = Path(art["log"]).read_text() if art.get("log") and Path(art["log"]).is_file() else ""
            ngv = re.findall(r"(ngspice-\d+) done", log_text)
            pt = {
                "id": cid, "variant": variant, "rate_v_per_s": rate, "rate_tag": tag, "primary_rate": primary,
                "process": proc, "temperature_c": temp, "klt_status": c.get("status"), "runtime_s": c.get("runtime_s"),
                "ngspice": ngv[0] if ngv else None,
                "diagnostics": [{"severity": g.get("severity"), "code": g.get("code"), "message": scrub(g.get("message", ""), run_dir)[:400]} for g in c.get("diagnostics", [])],
            }
            wp = Path(art["waveform"]) if art.get("waveform") else None
            if wp is not None and wp.is_file():
                wave = load_wave(wp)
                pt["extract"] = tx.analyze(wave, man["polarity"]["up"], man["polarity"]["down"])
                pt["trace_rows"] = write_trace(corners_dir / tag / f"{cid}.trace.csv.gz", wave)
                pt["vref_end_v"] = wave.get("v(vref)", [None])[-1]
            else:
                pt["extract"] = None
                pt["error_class"] = "model_not_found" if "could not find a valid modelname" in log_text else "no waveform retrieved"
            deck = Path(art["deck"]).read_text() if art.get("deck") and Path(art["deck"]).is_file() else "(no deck retrieved)"
            header = [f"# point: {SLUG} {variant} {tag} {cid}", f"# process={proc} temp={cr.fmt_temp(temp)}C rate={rate:g} V/s tstop={tstop_for(rate, man):.6g}s klt status: {c.get('status')}"]
            body = header + ["", "# ==== klt sim deck ====", *[f"| {ln}" for ln in deck.splitlines()], "", "# ==== klt diagnostics ====",
                             *[f"| {g['severity']}/{g['code']}: {g['message']}" for g in pt["diagnostics"]], "", "# ==== ngspice stdout+stderr ====", log_text.rstrip(), ""]
            (corners_dir / tag).mkdir(parents=True, exist_ok=True)
            (corners_dir / tag / f"{cid}.log").write_text(scrub("\n".join(body), run_dir))
            points.append(pt)
    return {"points": points, "requests": requests}


def f3(x, spec=".4f"):
    return "n/a" if x is None else f"{x:{spec}}"


def point_table(man: dict, points: list[dict], procs: list[str] | None = None) -> list[dict]:
    """One row per (process, temperature): primary-rate edges + guard grade. Never drops a corner."""
    prim = man["rates"]["primary_v_per_s"][0]
    half = prim * man["rates"]["half_rate_guard_factor"]
    tol = man["grading"]["rate_guard_tolerance_v"]
    by = {(p["rate_v_per_s"], p["id"]): p for p in points}
    rows = []
    for proc in procs or man["corners"]["process"]:
        for temp in man["corners"]["temperature_c"]:
            cid = corner_id(proc, temp)
            a, b = by.get((prim, cid)), by.get((half, cid))
            row = {"id": cid, "process": proc, "temperature_c": temp}
            ea = (a or {}).get("extract")
            eb = (b or {}).get("extract")
            if not ea:
                row.update(status="NO_RESULT (primary-rate segment: " + ((a or {}).get("error_class") or "not run / no report") + ")",
                           vup=None, vdn=None, hys=None, up_res="-", down_res="-")
            else:
                row.update(vup=ea["up"]["vdd_v"], vdn=ea["down"]["vdd_v"], hys=ea["hysteresis_v"],
                           up_res=ea["up"]["result"], down_res=ea["down"]["result"], max_step_v=ea["max_vdd_step_v"],
                           status="OK" if ea["verdict"] == "OK" else ea["verdict"])
                if eb:
                    g = tx.compare_rates(ea, eb, tol)
                    row["guard"] = g
                    if row["status"] == "OK" and g["grade"] != "consistent":
                        row["status"] = "RATE-DEPENDENT (not graded as a quasi-static result)"
                else:
                    row["guard"] = {"grade": "n/a (no half-rate waveform)"}
                    if row["status"] == "OK":
                        # no guard evidence -> not a graded quasi-static result (kept in the table, out of the binding set)
                        row["status"] = "UNGUARDED (half-rate sweep missing; not graded as a quasi-static result)"
            rows.append(row)
    return rows


def binding(rows: list[dict]) -> dict:
    ok = [r for r in rows if r["vup"] is not None and r["vdn"] is not None and r["hys"] is not None and r["status"] == "OK"]
    out = {"n_ok": len(ok), "n_total": len(rows)}
    if not ok:
        return out
    for key, fld in (("vpor_up", "vup"), ("vpor_down", "vdn"), ("hysteresis", "hys")):
        lo = min(ok, key=lambda r: r[fld])
        hi = max(ok, key=lambda r: r[fld])
        out[key] = {"min_v": lo[fld], "min_corner": lo["id"], "max_v": hi[fld], "max_corner": hi["id"]}
    return out


def render_md(rec: dict) -> str:
    man = rec["manifest_excerpt"]
    L = [f"# Record {rec['record_id']}", ""]
    L += sim_common.render_record_id_experiment(rec["record_id"], SLUG, man["title"])
    L.append(f"- **Claim**: {man['claim']}")
    L.append(f"- **Variant**: `{rec['variant']['name']}` -- {rec['variant']['description']}")
    L.append(f"- **Bias treatment**: {rec['variant']['bias_treatment']}")
    duts = ', '.join('`' + (n if '/' in n else 'design/netlist/' + n) + '`' for n in rec['variant']['dut_netlists'])
    L.append(f"- **Netlist provenance**: {rec['variant'].get('provenance') or 'schematic'} (testbench `{rec['variant']['schematic']}`; DUT spliced from {duts})")
    L += sim_common.render_pdk_tools_repo_state(rec)
    rg = rec.get("run_git") or {}
    if rg:
        L.append(f"- **Repo state at fleet-submit time**: `{rg.get('sha')}` on `{rg.get('branch')}`"
                 + (" (working tree DIRTY at submit time)" if rg.get("dirty") else " (clean working tree)")
                 + " -- the commit whose netlists the fleet simulated; the line above is the commit that extracted and wrote this record")
    t = rec["tools"]
    L.append(f"- **Fleet runner**: klt `{t['fleet_runner_klt']}` / `{t['fleet_ngspice']}` (client klt `{t['klt_client']}`); {t['fleet_note']}")
    L.append(f"- **Corner axis**: `{rec['matrix'].get('axis', 'main')}` -- {rec['matrix'].get('axis_note', '').rstrip('.')}. Never merged with the other axis's table.")
    L.append("- **Corner matrix run**: process " + ", ".join(rec["matrix"]["process"]) + "; temperature " + ", ".join(f"{cr.fmt_temp(x)} C" for x in rec["matrix"]["temperature_c"]) +
             f"; VDD is the swept variable (0 -> {rec['matrix']['peak_v']} V -> 0), no separate supply axis; sweep rates {', '.join(f'{r:g}' for r in rec['matrix']['rates_v_per_s'])} V/s (primary + half-rate guard). " +
             f"{rec['matrix']['n_corners']} process x temperature points; full matrix, no subset.")
    L.append("- **Statistical convention**: N/A (corner-matrix check; no mismatch Monte Carlo)")
    L.append("")
    L.append("## Measurement definitions (this campaign; none is a ratified bound)")
    for k, v in rec["definitions"].items():
        L.append(f"- **{k}**: {v}")
    L.append("")
    L.append("## Fleet submissions")
    L.append("| rate (V/s) | tstop (ms) | outcome | job id | runner klt | state | submitted at commit | refused earlier attempts |")
    L.append("|---|---|---|---|---|---|---|---|")
    for r in rec["requests"]:
        L.append(f"| {r['rate_v_per_s']:g} | {r['tstop_s'] * 1e3:.4g} | {r.get('outcome')} | {r.get('job_id')} | {r.get('runner_klt_version')} | {r.get('state')} | "
                 f"{r.get('submit_git') or 'unknown'} | {len(r.get('failed_earlier_attempts', []))} |")
    L.append("")
    prim = man["primary_rate"]
    L.append(f"## Per-corner results (primary rate {prim:g} V/s; all {len(rec['table'])} process x temperature points)")
    L.append("| corner | VPOR-up (V) | VPOR-down (V) | hysteresis (mV) | up edge | down edge | half-rate guard (up/down delta, mV) | status |")
    L.append("|---|---|---|---|---|---|---|---|")
    for r in rec["table"]:
        g = r.get("guard") or {}
        gtxt = g.get("grade", "-")
        if "up_delta_v" in g and "down_delta_v" in g:
            gtxt += f" ({g['up_delta_v'] * 1e3:+.2f}/{g['down_delta_v'] * 1e3:+.2f})"
        L.append(f"| {r['id']} | {f3(r['vup'])} | {f3(r['vdn'])} | {f3(None if r['hys'] is None else r['hys'] * 1e3, '.1f')} | {r['up_res']} | {r['down_res']} | {gtxt} | {r['status']} |")
    L.append("")
    b = rec["binding"]
    L.append("## Binding-corner table (EVIDENCE for a follow-on DR-003 amendment; not ratified, `spec/` untouched)")
    L.append(f"Computed over the {b['n_ok']} of {b['n_total']} corners with a clean, rate-consistent result.")
    if "vpor_up" in b:
        L.append("| metric | min (V or mV) | corner setting the min | max (V or mV) | corner setting the max |")
        L.append("|---|---|---|---|---|")
        L.append(f"| VPOR-up | {b['vpor_up']['min_v']:.4f} V | {b['vpor_up']['min_corner']} | {b['vpor_up']['max_v']:.4f} V | {b['vpor_up']['max_corner']} |")
        L.append(f"| VPOR-down | {b['vpor_down']['min_v']:.4f} V | {b['vpor_down']['min_corner']} | {b['vpor_down']['max_v']:.4f} V | {b['vpor_down']['max_corner']} |")
        L.append(f"| hysteresis | {b['hysteresis']['min_v'] * 1e3:.1f} mV | {b['hysteresis']['min_corner']} | {b['hysteresis']['max_v'] * 1e3:.1f} mV | {b['hysteresis']['max_corner']} |")
        m = rec["margin"]
        L.append("")
        L.append(f"Margin vs the DR-001 low rail ({m['rail_v']} V): VPOR-up,max = {m['vpor_up_max_v']:.4f} V ({m['vpor_up_max_corner']}) -> margin = rail - max(VPOR-up) = **{m['margin_mv']:+.0f} mV** "
                 f"(a positive number means the rail clears the worst-case-high rising threshold; a NEGATIVE number means VPOR-up exceeds the rail at that corner and the block would not release at the low rail). "
                 f"VPOR-up,min = {m['vpor_up_min_v']:.4f} V ({m['vpor_up_min_corner']}), i.e. {m['vpor_up_min_below_rail_mv']:+.0f} mV below the rail; the DR-001 high rail ({m['rail_hi_v']} V) is {m['vpor_up_max_below_hi_mv']:+.0f} mV above max(VPOR-up). "
                 "The binding side for 'release at the low rail' is max(VPOR-up); the binding side for 'not tripping inside the operating range' is VPOR-down,min.")
    else:
        L.append("No corner produced a clean result; no binding table can be formed.")
    L.append("")
    if rec.get("probe"):
        L.append("## Local single-corner cross-check (`--backend local`)")
        L.append(rec["probe"])
        L.append("")
    L.append("## Absent coverage (stated, not hidden)")
    for a in rec["absent_coverage"]:
        L.append(f"- {a}")
    L.append("")
    L.append("## Links")
    for k, v in rec["links"].items():
        L.append(f"- {k}: `{v}`")
    L.append(f"- **Timestamp / author**: {rec['timestamp']}, {rec['author']}")
    L.append(f"- **Supersedes**: {rec['supersedes'] or '(none)'}")
    L.append("")
    L.append(f"Written by `sim/{SLUG}/run_thresholds_campaign.py`. Append-only: never edit this file -- a correction is a new record with a `Supersedes` field (see `sim/README.md`).")
    L.append("")
    return "\n".join(L)


def cmd_record(args) -> int:
    man = load_manifest()
    run_dir = BUILD / args.run_id
    meta = json.loads((run_dir / "run.json").read_text())
    pin = cr.load_pin()
    pdk = cr.resolve_pdk(pin)
    git_info = cr.git_state()
    if git_info["dirty"] and not args.allow_dirty:
        raise SystemExit("working tree is dirty: commit first so the record carries a clean-tree SHA")
    now = datetime.now(timezone.utc)
    axis = meta.get("axis", "main")
    procs = processes(man, axis)
    ids = []
    for idx, variant in enumerate(args.variant or meta["variants"]):
        stamp = now if idx == 0 else datetime.now(timezone.utc)
        record_id = f"{stamp:%Y%m%d}-{stamp:%H%M%S}-{git_info['sha']}-{variant}" + ("" if axis == "main" else f"-{axis}")
        rec_dir, corners_dir, snap_dir = HERE / "records", HERE / "corners" / record_id, HERE / "netlist-snapshots" / record_id
        for pth in (rec_dir / f"{record_id}.md", rec_dir / f"{record_id}.json", corners_dir, snap_dir):
            if pth.exists():
                raise SystemExit(f"{pth} exists -- sim/ is append-only")
        res = analyze_variant(variant, run_dir, man, corners_dir)
        # per-request submit commit: a retried request ran at the retry's (clean) commit, not run.json's
        submit_git = {}
        for mf in sorted(run_dir.glob("run*.json"), key=lambda p: p.stat().st_mtime):
            m = json.loads(mf.read_text())
            for s in m.get("submit_results", []):
                if s.get("variant") == variant and s.get("status") not in (None, "NO-JSON"):
                    submit_git[s["tag"]] = m["git"]["sha"] + (" (DIRTY)" if m["git"].get("dirty") else " (clean)")
        for rq in res["requests"]:
            rq["submit_git"] = submit_git.get(rq["tag"])
        table = point_table(man, res["points"], procs)
        b = binding(table)
        margin = None
        if "vpor_up" in b:
            lo, hi = man["rails"]["low_v"], man["rails"]["high_v"]
            margin = {
                "rail_v": lo, "rail_hi_v": hi,
                "vpor_up_max_v": b["vpor_up"]["max_v"], "vpor_up_max_corner": b["vpor_up"]["max_corner"],
                "vpor_up_min_v": b["vpor_up"]["min_v"], "vpor_up_min_corner": b["vpor_up"]["min_corner"],
                "margin_mv": (lo - b["vpor_up"]["max_v"]) * 1e3,
                "vpor_up_min_below_rail_mv": (lo - b["vpor_up"]["min_v"]) * 1e3,
                "vpor_up_max_below_hi_mv": (hi - b["vpor_up"]["max_v"]) * 1e3,
            }
        snap_dir.mkdir(parents=True, exist_ok=True)
        for rate, _ in all_rates(man):
            d = run_dir / variant / rate_tag(rate)
            if (d / "netlist.spice").is_file():
                shutil.copyfile(d / "netlist.spice", snap_dir / f"{variant}_{rate_tag(rate)}.spice")
                shutil.copyfile(d / "request.json", snap_dir / f"{variant}_{rate_tag(rate)}.request.json")
            if (d / "report.json").is_file():
                (corners_dir / rate_tag(rate)).mkdir(parents=True, exist_ok=True)
                (corners_dir / rate_tag(rate) / "klt-report.json").write_text(scrub((d / "report.json").read_text(), run_dir))
        probe_text = ""
        if args.probe_note_file:
            probe_text = Path(args.probe_note_file).read_text().strip()
        runners = sorted({r.get("runner_klt_version") for r in res["requests"] if r.get("runner_klt_version")})
        ngs = sorted({p["ngspice"] for p in res["points"] if p["ngspice"]})
        v = man["variants"][variant]
        record = {
            "record_id": record_id,
            "timestamp": stamp.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "author": args.author or cr.default_author(),
            "supersedes": args.supersedes,
            "manifest_excerpt": {"title": man["title"], "claim": man["claim"], "primary_rate": man["rates"]["primary_v_per_s"][0]},
            "variant": {"name": variant, "description": v["description"], "bias_treatment": v["bias_treatment"], "schematic": "sim/" + SLUG + "/" + v["schematic"], "dut_netlists": v["dut_netlists"], "provenance": v.get("provenance"), "baseline_variant": v.get("baseline_variant")},
            "pdk": {"root": "<host $PDK_ROOT>", "variant": pdk.variant, "installed_commit": pdk.installed_commit, "pinned_commit": pin["open_pdks_commit"], "matches_pin": pdk.matches_pin,
                    "lib_file": f"$PDK_ROOT/{pdk.variant}/{pin['ngspice_lib']} (fleet: models.pdk={pdk.variant}, models.lib={MODEL_LIB})"},
            "tools": {
                "ngspice": f"{cr.first_line(['ngspice', '-v'])} (host; the grid ran on the fleet)",
                "xschem": cr.first_line(["xschem", "--version"]),
                "platform": cr.tool_versions()["platform"], "python": cr.tool_versions()["python"],
                "klt_client": meta["klt_client"], "fleet_runner_klt": ", ".join(runners) or "unknown", "fleet_ngspice": ", ".join(ngs) or "unknown",
                "fleet_note": "client/runner klt version skew accepted with batch.runner_version_check=warn; the runner ignores options.ngspice_init, so `set ng_nomodcheck` is carried in the netlist",
            },
            "git": git_info,
            "run_git": meta.get("git"),
            "matrix": {"axis": axis, "process": procs, "temperature_c": man["corners"]["temperature_c"], "peak_v": man["sweep"]["peak_v"],
                       "rates_v_per_s": [r for r, _ in all_rates(man)], "n_corners": len(procs) * len(man["corners"]["temperature_c"]), "is_subset": False,
                       "axis_note": "main = the 5 MOS process corners (the issue's 5x3 grid)" if axis == "main" else man["corners"]["passive_skew"]["note"]},
            "definitions": {**man["grading"]["definitions"], "sweep": man["sweep"]["construction"], "rates": man["rates"]["construction"], "edge extraction": f"VDD sample step <= {tx.MAX_BRACKET_V * 1e3:g} mV around an edge, linear interpolation inside the bracket; POR_RAW state evaluated for VDD >= {tx.V_VALID:g} V only"},
            "requests": res["requests"],
            "points": res["points"],
            "table": table,
            "binding": b,
            "margin": margin,
            "probe": probe_text,
            "absent_coverage": [c for c in man["absent_coverage"] if not (variant.endswith("-postlayout") and c.startswith("Post-layout parasitics are not included"))]
            + (["Post-layout scope: only por_comparator is extracted (lumped RC star per net, vertical-overlap coupling only, no lateral coupling, no distributed RC); the MOS models are rewritten 01v8 -> g5v0d10v5 because the layout lacks the hvi marker; bias_core and the testbench stimulus are schematic-level."] if variant.endswith("-postlayout") else []),
            "links": {
                "testbench": "sim/" + SLUG + "/" + v["schematic"], "manifest": f"sim/{SLUG}/experiment.json", "driver": f"sim/{SLUG}/run_thresholds_campaign.py",
                "extractor": f"sim/{SLUG}/threshold_extractor.py", "netlist_snapshots": f"sim/{SLUG}/netlist-snapshots/{record_id}/",
                "corners_dir": f"sim/{SLUG}/corners/{record_id}/", "json": f"sim/{SLUG}/records/{record_id}.json", "record": f"sim/{SLUG}/records/{record_id}.md",
            },
        }
        rec_dir.mkdir(parents=True, exist_ok=True)
        (rec_dir / f"{record_id}.json").write_text(json.dumps(record, indent=1, sort_keys=True, default=float) + "\n")
        (rec_dir / f"{record_id}.md").write_text(render_md(record))
        ids.append(record_id)
        print(f"record {variant}: {record_id}  ({b['n_ok']}/{b['n_total']} corners with a clean result)")
    return 0


def cmd_selftest(_args) -> int:
    return subprocess.call([sys.executable, "-I", str(HERE / "threshold_extractor.py")])


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    variants = ["ideal-bias", "real-bias-core", "ideal-bias-postlayout", "real-bias-core-postlayout"]
    r = sub.add_parser("run")
    r.add_argument("--variant", action="append", choices=variants)
    r.add_argument("--axis", choices=AXES, default="main", help="main = tt/ss/ff/sf/fs (the 5x3 grid); passive-skew = ll/hh resistor/cap sections (separate records)")
    r.add_argument("--jobs", type=int, default=2, help="concurrent fleet submissions (max 2)")
    r.add_argument("--run-id")
    r.add_argument("--retry-failed", action="store_true")
    r.add_argument("--capacity-wait", type=float, default=0)
    r.add_argument("--allow-dirty", action="store_true", help="debugging only; such a run must not be recorded")
    p = sub.add_parser("probe")
    p.add_argument("--variant", choices=variants, default="ideal-bias")
    p.add_argument("--rate", type=float)
    p.add_argument("--process", default="tt")
    p.add_argument("--temp", type=float, default=27)
    p.add_argument("--run-id")
    c = sub.add_parser("record")
    c.add_argument("--run-id", required=True)
    c.add_argument("--variant", action="append", choices=variants)
    c.add_argument("--probe-note-file")
    c.add_argument("--author")
    c.add_argument("--supersedes")
    c.add_argument("--allow-dirty", action="store_true")
    sub.add_parser("selftest")
    args = ap.parse_args(argv)
    return {"run": cmd_run, "probe": cmd_probe, "record": cmd_record, "selftest": cmd_selftest}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
